import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

test("keeps AI analytics extraction server-side and Team-reviewed", async () => {
  const [app, records, edgeFunction, migration] = await Promise.all([
    readFile(new URL("../app/CreatorPoolApp.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/supabase-records.ts", import.meta.url), "utf8"),
    readFile(new URL("../supabase/functions/analyze-submission-analytics/index.ts", import.meta.url), "utf8"),
    readFile(new URL("../supabase/migrations/20260826153000_ai_submission_analytics.sql", import.meta.url), "utf8"),
  ]);
  assert.match(app, /onAnalyze=\{analyzeSubmission\}/);
  assert.match(app, /Run AI analysis/);
  assert.match(app, /AI analyzing…/);
  assert.match(records, /functions\.invoke\("analyze-submission-analytics"/);
  assert.match(edgeFunction, /requiredSecret\("CLOUDFLARE_ACCOUNT_ID"\)/);
  assert.match(edgeFunction, /requiredSecret\("CLOUDFLARE_AI_API_TOKEN"\)/);
  assert.match(edgeFunction, /\.from\("submission-evidence"\)/);
  assert.match(edgeFunction, /submission\.creator_id !== userResult\.user\.id/);
  assert.match(edgeFunction, /callerProfile\?\.role === "marketing_admin"/);
  assert.match(edgeFunction, /api\.cloudflare\.com\/client\/v4\/accounts/);
  assert.match(edgeFunction, /@cf\/moondream\/moondream3\.1-9B-A2B/);
  assert.match(edgeFunction, /task: "query"/);
  assert.match(edgeFunction, /image: imageDataUrl/);
  assert.match(edgeFunction, /cloudflareModelResult/);
  assert.match(edgeFunction, /payload\?\.result \?\? payload/);
  assert.match(edgeFunction, /"usage" in result/);
  assert.match(edgeFunction, /result\?\.answer/);
  assert.match(edgeFunction, /isStructuredAnalytics/);
  assert.match(edgeFunction, /replaceAll\(",", ""\)/);
  assert.match(edgeFunction, /match\(\/\^\(-\?\\d\+/);
  assert.match(edgeFunction, /normalizedPlatform\(detectedPlatform\) === normalizedPlatform\(submission\.platform\)/);
  assert.match(edgeFunction, /booleanValue\(extracted\.valid_analytics_screenshot\)/);
  assert.match(edgeFunction, /const analyticsStatus = valid \? "ai_verified" : "ai_needs_review"/);
  assert.match(edgeFunction, /totalEngagement > 0/);
  assert.doesNotMatch(edgeFunction, /confidence >= 75/);
  assert.match(edgeFunction, /engagementExtractionPrompt/);
  assert.match(edgeFunction, /The play-triangle count is views and must not be counted as engagement/);
  assert.match(edgeFunction, /if \(totalEngagement <= 0\)/);
  assert.match(edgeFunction, /await runCloudflare\(engagementExtractionPrompt\(submission\.platform\), 300\)/);
  assert.match(edgeFunction, /focusedComponentTotal/);
  assert.match(edgeFunction, /When the same views metric appears as both an exact number/);
  assert.match(edgeFunction, /parseStructuredAnswer/);
  assert.match(edgeFunction, /A human Team member will make the final reward decision/);
  assert.match(migration, /calculate_submission_engagement_rate/);
  assert.match(migration, /total_engagement::numeric \/ new\.verified_views::numeric/);
  assert.match(migration, /auth\.role\(\) = 'service_role'/);
});

test("resumes a Creator's own pending application instead of reporting a false duplicate", async () => {
  const [app, migration, errors] = await Promise.all([
    readFile(new URL("../app/CreatorPoolApp.tsx", import.meta.url), "utf8"),
    readFile(new URL("../supabase/migrations/20260826213000_resumable_creator_application.sql", import.meta.url), "utf8"),
    readFile(new URL("../app/user-facing-errors.ts", import.meta.url), "utf8"),
  ]);
  assert.match(app, /rpc\("submit_my_creator_application"/);
  assert.match(migration, /pg_advisory_xact_lock/);
  assert.match(migration, /where creator_id = auth\.uid\(\)/);
  assert.match(migration, /creator_application_already_accepted/i);
  assert.match(migration, /status = 'in_review'/);
  assert.match(errors, /Your Creator Pool application has already been accepted/);
});

test("emails a declined Creator at the application email with the Team reason", async () => {
  const [app, edgeFunction] = await Promise.all([
    readFile(new URL("../app/CreatorPoolApp.tsx", import.meta.url), "utf8"),
    readFile(new URL("../supabase/functions/application-decision-email/index.ts", import.meta.url), "utf8"),
  ]);
  assert.match(app, /decline_reason:status==="Declined"\?reason:null/);
  assert.match(app, /functions\.invoke\("application-decision-email",\{body:\{applicationId:row\.id\}\}\)/);
  assert.match(edgeFunction, /callerProfile\?\.role !== "marketing_admin"/);
  assert.match(edgeFunction, /applicationData\.email \|\| creatorProfile\?\.email/);
  assert.match(edgeFunction, /String\(application\.decline_reason \|\| ""\)/);
  assert.match(edgeFunction, /Update on Your Meitu CreatorHub Application/);
  assert.match(edgeFunction, /Reason for declining:/);
  assert.match(edgeFunction, /decision_email_status: application\.status/);
});

test("ships the Creator Pool Hub product instead of the starter", async () => {
  const [page, app, layout, css, enhancements, publicCss, dashboardTheme, language, hosting, supabaseRecords, productionMigration, uniqueCreatorEmailMigration, campaignLimitMigration, userFacingErrors, deleteCreatorFunction] = await Promise.all([
    readFile(new URL("../app/page.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/CreatorPoolApp.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/layout.tsx", import.meta.url), "utf8"),
    readFile(new URL("../app/globals.css", import.meta.url), "utf8"),
    readFile(new URL("../app/form-enhancements.css", import.meta.url), "utf8"),
    readFile(new URL("../app/public-canva.css", import.meta.url), "utf8"),
    readFile(new URL("../app/dashboard-theme.css", import.meta.url), "utf8"),
    readFile(new URL("../app/portal-language.tsx", import.meta.url), "utf8"),
    readFile(new URL("../.openai/hosting.json", import.meta.url), "utf8"),
    readFile(new URL("../app/supabase-records.ts", import.meta.url), "utf8"),
    readFile(new URL("../supabase/006_production_completion.sql", import.meta.url), "utf8"),
    readFile(new URL("../supabase/migrations/20260826090000_unique_creator_contact_email.sql", import.meta.url), "utf8"),
    readFile(new URL("../supabase/migrations/20260826100000_campaign_submission_limit.sql", import.meta.url), "utf8"),
    readFile(new URL("../app/user-facing-errors.ts", import.meta.url), "utf8"),
    readFile(new URL("../supabase/functions/delete-creator/index.ts", import.meta.url), "utf8"),
  ]);
  assert.match(page, /CreatorPoolApp/);
  assert.match(app, /Good morning, \$\{name\}/);
  assert.match(app, /Real-time submissions across products/);
  assert.match(app, /activityMonths=Array\.from/);
  assert.doesNotMatch(app, /\[50,32,22\]/);
  assert.match(app, /Gabung Creator Pool/);
  assert.match(app, /const hasCreatorAccess=Boolean\(account&&\(account\.role==="team"\|\|account\.canAccessCreator\|\|account\.applicationStatus==="accepted"\)\)/);
  assert.match(app, /!hasCreatorAccess&&<button className="canva-button" onClick=\{onApply\}>/);
  assert.match(app, /!hasCreatorAccess&&<button className="canva-button canva-button-big" onClick=\{onApply\}>/);
  assert.match(layout, /Join Meitu Indonesia's official CreatorHub/);
  assert.match(layout, /og\.png/);
  assert.match(css, /@media\(max-width:800px\)/);
  assert.match(app, /expansion-social-column/);
  assert.match(app, /<th>Contact<\/th>/);
  assert.match(app, /secondary table-action-button/);
  assert.match(app, /primary table-action-button/);
  assert.match(app, /danger table-action-button/);
  assert.doesNotMatch(app, /Search creators, tasks, submissions/);
  assert.doesNotMatch(app, /Team email sign in/);
  assert.match(enhancements, /\.table-action-button/);
  assert.doesNotMatch(css, /\.table-wrap td:last-child button/);
  assert.match(app, /PortalLanguageProvider/);
  assert.match(app, /PortalLanguageSwitcher/);
  assert.match(app, /const isMarketingAdmin=data\?\.role==="marketing_admin"/);
  assert.match(app, /account\.role!=="team"\)return/);
  assert.match(app, /account\.role==="team"\)return/);
  assert.match(app, /creatorhub-team-\$\{account\.id\}/);
  assert.match(app, /window\.setInterval\(refresh,60_000\)/);
  assert.match(app, /document\.visibilityState==="hidden"/);
  assert.match(app, /canAccessCreator:isMarketingAdmin\|\|Boolean\(data\?\.can_access_creator\)\|\|applicationStatusValue==="accepted"/);
  assert.match(app, /account\?\.role==="team"&&<button className=\{space==="team"\?"active":""\}/);
  assert.match(app, /space-switch-creator-only/);
  assert.match(app, /next==="creator"&&account\.role!=="team"&&!account\.canAccessCreator/);
  assert.match(language, /creator-pool-language/);
  assert.match(language, /Bahasa Indonesia/);
  assert.match(language, /English/);
  assert.match(language, /\["placeholder", "title", "aria-label", "alt"\]/);
  assert.match(language, /\["Account", "Akun"\]/);
  assert.match(language, /\["Close engagement editor", "Tutup editor tingkat interaksi"\]/);
  assert.match(app, /application-step-body/);
  assert.match(enhancements, /@keyframes application-step-forward-in/);
  assert.match(app, /about-meitu-wordmark/);
  assert.match(app, /about-highlight-marquee/);
  assert.match(app, /\/canva\/meitu-wordmark\.png/);
  assert.match(publicCss, /@keyframes about-highlight-cycle/);
  assert.match(layout, /dashboard-theme\.css/);
  assert.match(dashboardTheme, /\.app-shell[\s\S]*--violet:\s*#f11d48/i);
  assert.match(dashboardTheme, /\.app-shell \.sidebar/);
  assert.match(dashboardTheme, /Keep all Meitu \/ BeautyCam \/ Wink product identities/);
  assert.match(app, /creator-home-stats/);
  assert.match(app, /suggestion-stack/);
  assert.match(app, /onPointerUp=\{event=>finishSuggestionSwipe/);
  assert.match(app, /campaign-progress-card/);
  assert.match(app, /Campaign Progress/);
  assert.match(app, /social-icon-row/);
  assert.match(app, /overview-tab-cards/);
  assert.match(app, /overview-reports/);
  assert.doesNotMatch(app, /eyebrow="Wednesday, 5 August"/);
  assert.doesNotMatch(app, /\["Reports","⌁"\]/);
  assert.match(enhancements, /\.overview-tab-card/);
  assert.doesNotMatch(app, /performance-bars/);
  assert.match(enhancements, /\.suggestion-card\.active/);
  const applicationsSection = app.slice(app.indexOf("function Applications"), app.indexOf("function Creators"));
  assert.doesNotMatch(applicationsSection, /application-manual-intro/);
  assert.match(applicationsSection, /manual-application-metrics/);
  assert.match(applicationsSection, /manual-application-table/);
  assert.match(applicationsSection, /expansion-application-filter/);
  assert.match(applicationsSection, /"Close":"View"/);
  assert.match(applicationsSection, />Edit<\/button>/);
  assert.match(applicationsSection, />Undo</);
  assert.match(applicationsSection, /updateExpansion\(request,"In review"\)/);
  assert.doesNotMatch(applicationsSection, /AI Verification|applicationVerification|autoApprove|ai-auto-accept|⇧ Export|Invite creator/);
  assert.doesNotMatch(applicationsSection, /<label>Application status/);
  assert.doesNotMatch(applicationsSection, /<th>Status<\/th>/);
  assert.match(applicationsSection, /data-label="Target Apps"/);
  assert.match(applicationsSection, /data-label="Requested Apps"/);
  assert.doesNotMatch(app, /status:"AI screening"/);
  assert.match(enhancements, /\.application-manual-intro/);
  assert.match(enhancements, /\.manual-application-table\s*\{[^}]*min-width:\s*0/);
  assert.match(enhancements, /\.manual-application-table \.product-stack\s*\{[^}]*flex-direction:\s*column/);
  assert.match(dashboardTheme, /\.manual-application-metrics/);
  const creatorsSection = app.slice(app.indexOf("function Creators"), app.indexOf("function Tasks"));
  assert.doesNotMatch(creatorsSection, /Invite creator/);
  assert.match(creatorsSection, /onClick=\{exportCreators\}>Export list/);
  assert.match(creatorsSection, /creator-pool-creators\.csv/);
  assert.match(creatorsSection, /URL\.createObjectURL/);
  assert.match(creatorsSection, /creator-pagination/);
  assert.doesNotMatch(creatorsSection, /<Avatar/);
  assert.match(creatorsSection, /creator-cell-without-avatar/);
  assert.match(creatorsSection, /Campaigns submitted record/);
  assert.match(creatorsSection, /creator-submitted-record/);
  assert.match(creatorsSection, /Permanently delete Creator/);
  assert.match(creatorsSection, /deleteConfirmation!=="DELETE"/);
  assert.match(creatorsSection, /10 \/ page/);
  assert.match(creatorsSection, /100 \/ page/);
  assert.match(supabaseRecords, /functions\.invoke\("delete-creator"/);
  assert.match(deleteCreatorFunction, /caller\?\.role !== "marketing_admin"/);
  assert.match(deleteCreatorFunction, /target\.role === "marketing_admin"/);
  assert.match(deleteCreatorFunction, /admin\.auth\.admin\.deleteUser\(creatorId\)/);
  assert.match(deleteCreatorFunction, /\.from\("submission-evidence"\)\.remove\(evidenceKeys\)/);
  assert.match(app, /team-campaign-cards/);
  assert.match(app, /team-profile-trigger/);
  assert.match(app, /team-profile-dropdown/);
  assert.match(app, /team-profile-language/);
  assert.match(app, /function PortalProfileMenu/);
  assert.match(app, /creator-profile-control/);
  const topbarSection = app.slice(app.indexOf('<header className="topbar"'), app.indexOf('<div className="workspace">'));
  assert.match(topbarSection, /PortalProfileMenu/);
  assert.doesNotMatch(topbarSection, /Notifications|Buat kiriman/);
  assert.doesNotMatch(app, /space==="team"\?"Create campaign"/);
  assert.doesNotMatch(app.slice(app.indexOf("team-profile-dropdown"),app.indexOf("</header>\n      <div className=\"workspace\"")), /Appearance/);
  assert.match(app, /creator-campaign-cards/);
  assert.match(app, /creator-campaign-submit/);
  assert.doesNotMatch(app.slice(app.indexOf("const teamNav"),app.indexOf("const creatorNav")), /Campaign Completion Streak/);
  assert.match(app, /function ApplicationsHub/);
  assert.match(app, /Creator applications","Apply New Apps/);
  const applicationsHub = app.slice(app.indexOf("function ApplicationsHub"),app.indexOf("function StreakVipReview"));
  assert.ok(applicationsHub.indexOf("application-hub-metrics") < applicationsHub.indexOf("application-hub-tabs"));
  assert.match(applicationsHub, /activeStatuses/);
  assert.doesNotMatch(applicationsHub, /Streak VIP Code|streakRequests|StreakVipReview/);
  assert.match(enhancements, /\.application-hub-tabs/);
  assert.match(applicationsSection, /"Close":"View"/);
  assert.match(applicationsSection, />Edit<\/button>/);
  assert.match(enhancements, /Text labels replace the icon-only Applications actions/);
  assert.match(enhancements, /\.application-actions \.table-action-button[\s\S]*min-width:\s*64px[\s\S]*font-size:\s*8\.5px/);
  assert.match(enhancements, /\.table-action-button::before,[\s\S]*content:\s*none !important/);
  assert.doesNotMatch(enhancements, /Outlined icon-plus-label actions inspired by colored niche chips/);
  const campaignsSection = app.slice(app.indexOf("function Tasks"), app.indexOf("function Submissions"));
  assert.doesNotMatch(campaignsSection, /Campaign code/);
  assert.match(campaignsSection, /Campaign Collaboration Flow|campaign-collaboration-flow/);
  assert.match(campaignsSection, /Submit within 7 days after posting/);
  assert.match(campaignsSection, /The Meitu system checks the qualification of your post/);
  assert.doesNotMatch(campaignsSection, /Only campaigns for your registered apps/);
  assert.match(campaignsSection, /creator-campaign-description/);
  assert.match(campaignsSection, /Submission Limit Reached/);
  assert.match(campaignsSection, /campaignSubmissionCount\(submissions,task\)/);
  assert.match(app, /creator-submission-cards/);
  assert.match(app, /creator-submission-app-date/);
  assert.match(app, /creator-submission-details/);
  assert.match(app, /creator-reward-summary/);
  assert.match(app, /creator-leaderboard-podium/);
  const leaderboardSection = app.slice(app.indexOf("function Leaderboard"), app.indexOf("function Profile"));
  assert.doesNotMatch(leaderboardSection, /<Avatar/);
  assert.doesNotMatch(leaderboardSection, /Winning posts|leaderboard-winner-posts/);
  assert.match(leaderboardSection, /Top Monthly Viewers/);
  assert.match(leaderboardSection, /Top Gainers/);
  assert.match(app, /profile-social-options/);
  assert.match(app, /Contact email/);
  assert.doesNotMatch(app, /Change profile picture/);
  assert.doesNotMatch(app, /profile-photo-editor|upload-profile-button/);
  assert.doesNotMatch(language, /Profile photo|profile picture|Change profile photo|JPG, PNG, or WEBP image/);
  assert.match(app, /profile-identity-editor-no-avatar/);
  assert.match(app, /save_my_creator_profile/);
  assert.match(uniqueCreatorEmailMigration, /guard_creator_contact_email/);
  assert.match(uniqueCreatorEmailMigration, /profile\.id <> new\.creator_id/);
  assert.match(uniqueCreatorEmailMigration, /settings\.creator_id <> new\.creator_id/);
  assert.match(uniqueCreatorEmailMigration, /errcode = '23505'/);
  assert.match(userFacingErrors, /This email has already been registered\. Please try using a different email\./);
  assert.match(app, /name:profile\?\.displayName\|\|application\.name/);
  assert.match(app, /email:profile\?\.contactEmail\|\|application\.email/);
  assert.match(app, /category:profile\?\.niches\|\|application\.category/);
  assert.match(app, /selectedPlatforms\.includes\("TikTok"\)/);
  assert.doesNotMatch(app, /page==="Settings"/);
  assert.doesNotMatch(app, /<label>Bio/);
  assert.match(enhancements, /\.creator-campaign-submit[\s\S]*linear-gradient\(120deg,#080808[\s\S]*#f11d48/);
  assert.match(enhancements, /\.creator-reward-summary\s*\{\s*grid-template-columns:\s*repeat\(3/);
  assert.match(app, /function ManualSubmissions/);
  assert.match(app, /creator-submission-app-filter/);
  assert.match(app, /filter-\$\{product\.toLowerCase\(\)\}/);
  assert.match(app, /creator-summary-table/);
  assert.match(app, /table-row-open-button[\s\S]{0,260}event\.stopPropagation\(\);onRow\(s\)/);
  assert.match(app, /reward-payment-table/);
  assert.match(app, /function ManualSubmissionModal/);
  const manualSubmissions = app.slice(app.indexOf("function ManualSubmissions"), app.indexOf("function EnhancedRewards"));
  assert.doesNotMatch(manualSubmissions, /Engagement rate analyzer|submission-ai-method/);
  assert.match(manualSubmissions, /Send VIP code/);
  assert.match(dashboardTheme, /\.manual-submission-creator > \.avatar\s*\{\s*display:none/);
  assert.match(dashboardTheme, /grid-template-columns:112px 100px/);
  assert.match(dashboardTheme, /grid-template-columns:minmax\(210px,1\.1fr\)[\s\S]*282px/);
  assert.match(manualSubmissions, /submission-creator-social/);
  assert.match(manualSubmissions, /submission-creator-name/);
  assert.match(manualSubmissions, /onOpenCreator\(item\)/);
  assert.match(manualSubmissions, /socialUsernameFromUrl/);
  assert.match(manualSubmissions, /postAddress\.includes\("instagram\.com\//);
  assert.match(manualSubmissions, /postAddress\.includes\("threads\.net\//);
  assert.match(manualSubmissions, /postAddress\.includes\("tiktok\.com\//);
  assert.match(manualSubmissions, /Open profile/);
  assert.match(manualSubmissions, /Edit rate/);
  assert.match(manualSubmissions, /View analytics screenshot/);
  assert.match(manualSubmissions, /itemStatus==="In review"&&<button[^>]*manual-engagement-button/);
  assert.match(manualSubmissions, /Open analytics screenshot/);
  assert.match(manualSubmissions, /Update the engagement rate and final decision from one place/);
  assert.match(manualSubmissions, /editedStatus/);
  assert.match(manualSubmissions, />Edit</);
  assert.match(manualSubmissions, /Filter by app and status/);
  assert.match(manualSubmissions, /qualified-submission-reward/);
  assert.match(manualSubmissions, /Fill payment form/);
  assert.match(app, /function EnhancedRewards/);
  assert.match(app, /VIP Code: \$\{item\.vipCode\}/);
  assert.match(app, /VIP code saved and sent to the Creator Rewards portal/);
  assert.doesNotMatch(app.slice(app.indexOf("function EnhancedRewards"),app.indexOf("function ManualReports")), /reward-history-trigger|selectedRewardId/);
  assert.match(app, /reward-history-card-expanded/);
  assert.match(app, /reward-history-summary/);
  assert.match(enhancements, /\.podium-rank-1\s*\{\s*order:\s*2/);
  assert.match(enhancements, /\.podium-rank-2\s*\{\s*order:\s*1/);
  assert.match(enhancements, /\.campaign-meitu \.creator-campaign-app b/);
  assert.match(enhancements, /\.campaign-meitu \.creator-campaign-app b\s*\{\s*background:\s*linear-gradient\(120deg,#ff7894,#f11d48/);
  assert.match(enhancements, /\.suggestion-app-wink\s*\{[^}]*linear-gradient\(145deg,#9478ff,#6557ff,#20b8ef/);
  assert.match(dashboardTheme, /\.app-shell \.badge-in-review\s*\{[^}]*linear-gradient\(135deg,#fff6d9,#ffe39a/);
  assert.match(enhancements, /\.reward-payment-action \.payment-form-link\s*\{[^}]*display:\s*inline-flex/);
  assert.match(enhancements, /\.onboarding-niche-grid button::before/);
  assert.match(enhancements, /\.portal-language-switcher select\s*\{[^}]*font-size:\s*10px/);
  assert.match(enhancements, /Independent desktop columns keep expanded submission cards/);
  assert.match(enhancements, /\.creator-submission-columns\s*\{[^}]*grid-template-columns:repeat\(2/);
  assert.match(enhancements, /@keyframes profile-choice-pop/);
  assert.match(enhancements, /\.creator-submission-app-filter/);
  assert.match(enhancements, /Profile niche choices mirror the registration icons and color system/);
  assert.match(enhancements, /\.settings-niche-grid button::before/);
  assert.match(dashboardTheme, /Keep portal table headings aligned with their centered column content/);
  assert.match(dashboardTheme, /\.app-shell table th,[\s\S]*text-align:\s*center/);
  assert.match(dashboardTheme, /Product gradients identify the app on both Team and Creator submission lists/);
  assert.match(dashboardTheme, /\.creator-submission-card \.product-meitu,[\s\S]*linear-gradient\(120deg,#ff7894,#f11d48,#c90d35\)/);
  assert.match(dashboardTheme, /\.creator-campaign-card footer button\s*\{[^}]*font-size:\s*9px/);
  assert.match(dashboardTheme, /Desktop portal typography/);
  assert.match(dashboardTheme, /@media \(min-width:\s*1000px\)/);
  assert.match(dashboardTheme, /\.app-shell \.page-head h1\s*\{\s*font-size:\s*34px/);
  assert.match(dashboardTheme, /\.app-shell table th\s*\{\s*font-size:\s*10\.5px/);
  assert.match(dashboardTheme, /\.app-shell \.sidebar nav button,[\s\S]*font-size:\s*14\.5px/);
  assert.match(dashboardTheme, /\.task-preview-links a:visited\s*\{[^}]*color:\s*#fff !important/);
  assert.match(dashboardTheme, /submission-dialog:not\(\.manual-submission-dialog\)[\s\S]*selected-submission-task span\s*\{\s*display:none/);
  assert.match(dashboardTheme, /submission-dialog \.task-reward-callout b,[\s\S]*font-size:14px/);
  assert.match(dashboardTheme, /submission-dialog \.ai-calculation-note b,[\s\S]*font-size:11px/);
  assert.match(dashboardTheme, /submission-dialog \.upload b\s*\{[^}]*font-size:12px/);
  assert.match(dashboardTheme, /Creator identity columns stay left-aligned/);
  assert.match(dashboardTheme, /\.app-shell-team \.product-meitu[\s\S]*linear-gradient\(120deg,#ff7894,#f11d48,#c90d35\)/);
  assert.match(dashboardTheme, /\.app-shell-creator \.monthly-leaderboard-filter/);
  assert.match(app, /app-shell-\$\{space\}/);
  assert.match(app, /application-donut/);
  assert.match(dashboardTheme, /chart-bar-tooltip/);
  assert.match(dashboardTheme, /creator-niche-filters/);
  assert.match(creatorsSection, /selectedNiches/);
  assert.match(creatorsSection, /toggleNiche/);
  assert.match(creatorsSection, /aria-pressed=\{selectedNiches\.includes\(item\)\}/);
  assert.match(creatorsSection, /selectedNiches\.some\(item=>rowNiches\.includes\(item\)\)/);
  assert.match(dashboardTheme, /\.app-shell \.social-account-list > a\s*\{[^}]*height:52px/);
  assert.match(dashboardTheme, /\.creator-niche-stack/);
  assert.match(app, /Payment form<select/);
  assert.match(app, /historyMonth/);
  assert.doesNotMatch(app, /paymentFormChecked:checked\?1:0,status:checked/);
  assert.match(supabaseRecords, /loadPortalRecords/);
  assert.match(supabaseRecords, /campaign_submissions/);
  assert.match(supabaseRecords, /upsertRewardRecord/);
  assert.match(productionMigration, /submission-evidence/);
  assert.match(productionMigration, /creator-avatars/);
  assert.match(productionMigration, /guard_creator_submission_update/);
  assert.match(productionMigration, /supabase_realtime/);
  assert.match(app, /openSubmissionIds/);
  assert.match(app, /creator-submission-column-\$\{column===0\?"left":"right"\}/);
  assert.doesNotMatch(app.slice(app.indexOf("function ManualSubmissions"),app.indexOf("function ManualReviewDrawer")), /selectedSubmissionId/);
  assert.match(app, /cta-ripple-elements/);
  assert.match(app, /--ripple-x/);
  assert.match(publicCss, /@keyframes cta-cursor-ripple/);
  assert.match(publicCss, /\.cta-ripple-elements/);
  assert.match(publicCss, /Neon app-color atmosphere for the Creator Pool welcome hero/);
  assert.match(publicCss, /rgba\(255,125,230,\.2\)/);
  assert.match(publicCss, /Keep the desktop journey copy aligned between its number and icon/);
  assert.match(language, /Alur Kolaborasi Kampanye/);
  assert.match(app, /function InteractiveApplicationModal/);
  assert.match(app, /Array\.from\(\{length:8\}/);
  assert.match(app, /I have read and agree to the Terms & Conditions and the processing of personal data/);
  const publicSite = app.slice(app.indexOf("function PublicSite"),app.indexOf("function ApplicationModal"));
  assert.match(publicSite, /At <b>Meitu<\/b>/);
  assert.match(publicSite, /<b>250 million users worldwide<\/b>/);
  assert.match(publicSite, /How To Register/);
  assert.match(publicCss, /overflow-x:\s*clip/);
  assert.match(publicCss, /\.canva-public \.canva-nav\s*\{[\s\S]*position:\s*sticky/);
  const interactiveApplication = app.slice(app.indexOf("function InteractiveApplicationModal"),app.indexOf("function ManualSubmissions"));
  assert.doesNotMatch(interactiveApplication, /One short section at a time|Satu bagian singkat setiap kali/);
  assert.match(enhancements, /One button model for the public and portal language controls/);
  assert.match(enhancements, /text-align-last:\s*center/);
  assert.match(enhancements, /\.interactive-progress > div:first-child b\s*\{[^}]*font-size:11px/);
  assert.match(language, /\["Fashion", "Fashion"\]/);
  assert.match(language, /\["Travel & Nature", "Travel & Alam"\]/);
  assert.match(language, /\["Comedy & Skits", "Komedi & Hiburan"\]/);
  assert.match(language, /\["Tech & Gadgets", "Teknologi & Gadget"\]/);
  assert.match(language, /\["Gaming", "Game"\]/);
  assert.match(language, /\["Editing \/ Photography", "Editing \/ Fotografi"\]/);
  assert.match(publicCss, /Story-led public sections/);
  assert.match(publicCss, /animation-timeline:view\(\)/);
  assert.match(language, /Social & Channel Links/);
  const creatorHome = app.slice(app.indexOf("function CreatorHome"),app.indexOf("function Leaderboard"));
  assert.match(creatorHome, /const progressTasks=/);
  assert.match(creatorHome, /Campaigns submitted/);
  assert.match(creatorHome, /Total views/);
  assert.match(creatorHome, /Total earnings/);
  assert.match(creatorHome, /home-stat-icon-/);
  assert.match(dashboardTheme, /--icon-bottom/);
  assert.match(dashboardTheme, /box-shadow:inset 2px 2px 3px/);
  assert.match(dashboardTheme, /home-stat-icon-position\s*\{[^}]*--icon-top:#4b4547/);
  assert.match(creatorHome, /const profileComplete=/);
  assert.match(creatorHome, /const unsubmittedTasks=/);
  assert.match(creatorHome, /const paymentNeeded=/);
  assert.match(creatorHome, /const suggestionSignature=/);
  assert.match(creatorHome, /MAX_POSTS_PER_CAMPAIGN/);
  assert.doesNotMatch(creatorHome, /Completion Streak|VIP Code History|saveRequest/);
  assert.match(campaignLimitMigration, /existing_post_count >= 3/);
  assert.match(campaignLimitMigration, /pg_advisory_xact_lock/);
  assert.match(campaignLimitMigration, /enforce_campaign_submission_limit/);
  assert.match(userFacingErrors, /CAMPAIGN_SUBMISSION_LIMIT_REACHED/i);
  const creatorManualSubmissions = app.slice(app.indexOf("function ManualSubmissions"),app.indexOf("function ManualSubmissionModal"));
  assert.match(creatorManualSubmissions, /<dt>Posting date<\/dt><dd>\{displayDate\(item\.publishedAt\)\}<\/dd>/);
  assert.match(enhancements, /grid-template-columns:56px minmax\(190px,1fr\) minmax\(180px,\.72fr\)/);
  assert.match(enhancements, /leaderboard-top-five-head span:first-child \{ grid-column:1 \/ 3/);
  assert.match(dashboardTheme, /reward-history-summary \.product-meitu/);
  assert.equal((app.match(/placeholder="81234567890"/g) || []).length, 3);
  assert.equal((app.match(/Do not include a leading zero\./g) || []).length, 3);
  assert.doesNotMatch(app + language, /placeholder="818227037"|The number is saved as|Nomor tersimpan sebagai|Do not include a leading zero\. Preview/);
  assert.match(app + language, /videos posted in August are recapped on 31 August and paid around 30 September–15 October/);
  assert.match(app + language, /video yang diposting pada Agustus direkap 31 Agustus dan dibayar sekitar 30 September–15 Oktober/);
  assert.doesNotMatch(app + language, /video posted in June|video yang diposting pada Juni/);
  assert.match(publicCss, /pointer-events: none/);
  assert.match(hosting, /"d1": null/);
  assert.match(hosting, /"r2": null/);
  assert.doesNotMatch(page + app + layout, /codex-preview|react-loading-skeleton/i);
});
