export type CountryCallingCode = { label: string; flag: string; code: string };

// ISO countries and commonly selectable territories with their international calling codes.
export const countryCallingCodes: CountryCallingCode[] = [
  {label:"Afghanistan",flag:"🇦🇫",code:"+93"},{label:"Albania",flag:"🇦🇱",code:"+355"},{label:"Algeria",flag:"🇩🇿",code:"+213"},{label:"American Samoa",flag:"🇦🇸",code:"+1684"},{label:"Andorra",flag:"🇦🇩",code:"+376"},{label:"Angola",flag:"🇦🇴",code:"+244"},{label:"Anguilla",flag:"🇦🇮",code:"+1264"},{label:"Antigua and Barbuda",flag:"🇦🇬",code:"+1268"},{label:"Argentina",flag:"🇦🇷",code:"+54"},{label:"Armenia",flag:"🇦🇲",code:"+374"},{label:"Aruba",flag:"🇦🇼",code:"+297"},{label:"Australia",flag:"🇦🇺",code:"+61"},{label:"Austria",flag:"🇦🇹",code:"+43"},{label:"Azerbaijan",flag:"🇦🇿",code:"+994"},
  {label:"Bahamas",flag:"🇧🇸",code:"+1242"},{label:"Bahrain",flag:"🇧🇭",code:"+973"},{label:"Bangladesh",flag:"🇧🇩",code:"+880"},{label:"Barbados",flag:"🇧🇧",code:"+1246"},{label:"Belarus",flag:"🇧🇾",code:"+375"},{label:"Belgium",flag:"🇧🇪",code:"+32"},{label:"Belize",flag:"🇧🇿",code:"+501"},{label:"Benin",flag:"🇧🇯",code:"+229"},{label:"Bermuda",flag:"🇧🇲",code:"+1441"},{label:"Bhutan",flag:"🇧🇹",code:"+975"},{label:"Bolivia",flag:"🇧🇴",code:"+591"},{label:"Bonaire, Sint Eustatius and Saba",flag:"🇧🇶",code:"+599"},{label:"Bosnia and Herzegovina",flag:"🇧🇦",code:"+387"},{label:"Botswana",flag:"🇧🇼",code:"+267"},{label:"Brazil",flag:"🇧🇷",code:"+55"},{label:"British Indian Ocean Territory",flag:"🇮🇴",code:"+246"},{label:"British Virgin Islands",flag:"🇻🇬",code:"+1284"},{label:"Brunei",flag:"🇧🇳",code:"+673"},{label:"Bulgaria",flag:"🇧🇬",code:"+359"},{label:"Burkina Faso",flag:"🇧🇫",code:"+226"},{label:"Burundi",flag:"🇧🇮",code:"+257"},
  {label:"Cabo Verde",flag:"🇨🇻",code:"+238"},{label:"Cambodia",flag:"🇰🇭",code:"+855"},{label:"Cameroon",flag:"🇨🇲",code:"+237"},{label:"Canada",flag:"🇨🇦",code:"+1"},{label:"Cayman Islands",flag:"🇰🇾",code:"+1345"},{label:"Central African Republic",flag:"🇨🇫",code:"+236"},{label:"Chad",flag:"🇹🇩",code:"+235"},{label:"Chile",flag:"🇨🇱",code:"+56"},{label:"China",flag:"🇨🇳",code:"+86"},{label:"Christmas Island",flag:"🇨🇽",code:"+61"},{label:"Cocos (Keeling) Islands",flag:"🇨🇨",code:"+61"},{label:"Colombia",flag:"🇨🇴",code:"+57"},{label:"Comoros",flag:"🇰🇲",code:"+269"},{label:"Congo",flag:"🇨🇬",code:"+242"},{label:"Congo (DRC)",flag:"🇨🇩",code:"+243"},{label:"Cook Islands",flag:"🇨🇰",code:"+682"},{label:"Costa Rica",flag:"🇨🇷",code:"+506"},{label:"Côte d’Ivoire",flag:"🇨🇮",code:"+225"},{label:"Croatia",flag:"🇭🇷",code:"+385"},{label:"Cuba",flag:"🇨🇺",code:"+53"},{label:"Curaçao",flag:"🇨🇼",code:"+599"},{label:"Cyprus",flag:"🇨🇾",code:"+357"},{label:"Czechia",flag:"🇨🇿",code:"+420"},
  {label:"Denmark",flag:"🇩🇰",code:"+45"},{label:"Djibouti",flag:"🇩🇯",code:"+253"},{label:"Dominica",flag:"🇩🇲",code:"+1767"},{label:"Dominican Republic",flag:"🇩🇴",code:"+1809"},{label:"Dominican Republic",flag:"🇩🇴",code:"+1829"},{label:"Dominican Republic",flag:"🇩🇴",code:"+1849"},
  {label:"Ecuador",flag:"🇪🇨",code:"+593"},{label:"Egypt",flag:"🇪🇬",code:"+20"},{label:"El Salvador",flag:"🇸🇻",code:"+503"},{label:"Equatorial Guinea",flag:"🇬🇶",code:"+240"},{label:"Eritrea",flag:"🇪🇷",code:"+291"},{label:"Estonia",flag:"🇪🇪",code:"+372"},{label:"Eswatini",flag:"🇸🇿",code:"+268"},{label:"Ethiopia",flag:"🇪🇹",code:"+251"},
  {label:"Falkland Islands",flag:"🇫🇰",code:"+500"},{label:"Faroe Islands",flag:"🇫🇴",code:"+298"},{label:"Fiji",flag:"🇫🇯",code:"+679"},{label:"Finland",flag:"🇫🇮",code:"+358"},{label:"France",flag:"🇫🇷",code:"+33"},{label:"French Guiana",flag:"🇬🇫",code:"+594"},{label:"French Polynesia",flag:"🇵🇫",code:"+689"},
  {label:"Gabon",flag:"🇬🇦",code:"+241"},{label:"Gambia",flag:"🇬🇲",code:"+220"},{label:"Georgia",flag:"🇬🇪",code:"+995"},{label:"Germany",flag:"🇩🇪",code:"+49"},{label:"Ghana",flag:"🇬🇭",code:"+233"},{label:"Gibraltar",flag:"🇬🇮",code:"+350"},{label:"Greece",flag:"🇬🇷",code:"+30"},{label:"Greenland",flag:"🇬🇱",code:"+299"},{label:"Grenada",flag:"🇬🇩",code:"+1473"},{label:"Guadeloupe",flag:"🇬🇵",code:"+590"},{label:"Guam",flag:"🇬🇺",code:"+1671"},{label:"Guatemala",flag:"🇬🇹",code:"+502"},{label:"Guernsey",flag:"🇬🇬",code:"+44"},{label:"Guinea",flag:"🇬🇳",code:"+224"},{label:"Guinea-Bissau",flag:"🇬🇼",code:"+245"},{label:"Guyana",flag:"🇬🇾",code:"+592"},
  {label:"Haiti",flag:"🇭🇹",code:"+509"},{label:"Honduras",flag:"🇭🇳",code:"+504"},{label:"Hong Kong",flag:"🇭🇰",code:"+852"},{label:"Hungary",flag:"🇭🇺",code:"+36"},
  {label:"Iceland",flag:"🇮🇸",code:"+354"},{label:"India",flag:"🇮🇳",code:"+91"},{label:"Indonesia",flag:"🇮🇩",code:"+62"},{label:"Iran",flag:"🇮🇷",code:"+98"},{label:"Iraq",flag:"🇮🇶",code:"+964"},{label:"Ireland",flag:"🇮🇪",code:"+353"},{label:"Isle of Man",flag:"🇮🇲",code:"+44"},{label:"Israel",flag:"🇮🇱",code:"+972"},{label:"Italy",flag:"🇮🇹",code:"+39"},
  {label:"Jamaica",flag:"🇯🇲",code:"+1876"},{label:"Jamaica",flag:"🇯🇲",code:"+1658"},{label:"Japan",flag:"🇯🇵",code:"+81"},{label:"Jersey",flag:"🇯🇪",code:"+44"},{label:"Jordan",flag:"🇯🇴",code:"+962"},
  {label:"Kazakhstan",flag:"🇰🇿",code:"+7"},{label:"Kenya",flag:"🇰🇪",code:"+254"},{label:"Kiribati",flag:"🇰🇮",code:"+686"},{label:"Kosovo",flag:"🇽🇰",code:"+383"},{label:"Kuwait",flag:"🇰🇼",code:"+965"},{label:"Kyrgyzstan",flag:"🇰🇬",code:"+996"},
  {label:"Laos",flag:"🇱🇦",code:"+856"},{label:"Latvia",flag:"🇱🇻",code:"+371"},{label:"Lebanon",flag:"🇱🇧",code:"+961"},{label:"Lesotho",flag:"🇱🇸",code:"+266"},{label:"Liberia",flag:"🇱🇷",code:"+231"},{label:"Libya",flag:"🇱🇾",code:"+218"},{label:"Liechtenstein",flag:"🇱🇮",code:"+423"},{label:"Lithuania",flag:"🇱🇹",code:"+370"},{label:"Luxembourg",flag:"🇱🇺",code:"+352"},
  {label:"Macao",flag:"🇲🇴",code:"+853"},{label:"Madagascar",flag:"🇲🇬",code:"+261"},{label:"Malawi",flag:"🇲🇼",code:"+265"},{label:"Malaysia",flag:"🇲🇾",code:"+60"},{label:"Maldives",flag:"🇲🇻",code:"+960"},{label:"Mali",flag:"🇲🇱",code:"+223"},{label:"Malta",flag:"🇲🇹",code:"+356"},{label:"Marshall Islands",flag:"🇲🇭",code:"+692"},{label:"Martinique",flag:"🇲🇶",code:"+596"},{label:"Mauritania",flag:"🇲🇷",code:"+222"},{label:"Mauritius",flag:"🇲🇺",code:"+230"},{label:"Mayotte",flag:"🇾🇹",code:"+262"},{label:"Mexico",flag:"🇲🇽",code:"+52"},{label:"Micronesia",flag:"🇫🇲",code:"+691"},{label:"Moldova",flag:"🇲🇩",code:"+373"},{label:"Monaco",flag:"🇲🇨",code:"+377"},{label:"Mongolia",flag:"🇲🇳",code:"+976"},{label:"Montenegro",flag:"🇲🇪",code:"+382"},{label:"Montserrat",flag:"🇲🇸",code:"+1664"},{label:"Morocco",flag:"🇲🇦",code:"+212"},{label:"Mozambique",flag:"🇲🇿",code:"+258"},{label:"Myanmar",flag:"🇲🇲",code:"+95"},
  {label:"Namibia",flag:"🇳🇦",code:"+264"},{label:"Nauru",flag:"🇳🇷",code:"+674"},{label:"Nepal",flag:"🇳🇵",code:"+977"},{label:"Netherlands",flag:"🇳🇱",code:"+31"},{label:"New Caledonia",flag:"🇳🇨",code:"+687"},{label:"New Zealand",flag:"🇳🇿",code:"+64"},{label:"Nicaragua",flag:"🇳🇮",code:"+505"},{label:"Niger",flag:"🇳🇪",code:"+227"},{label:"Nigeria",flag:"🇳🇬",code:"+234"},{label:"Niue",flag:"🇳🇺",code:"+683"},{label:"Norfolk Island",flag:"🇳🇫",code:"+672"},{label:"North Korea",flag:"🇰🇵",code:"+850"},{label:"North Macedonia",flag:"🇲🇰",code:"+389"},{label:"Northern Mariana Islands",flag:"🇲🇵",code:"+1670"},{label:"Norway",flag:"🇳🇴",code:"+47"},
  {label:"Oman",flag:"🇴🇲",code:"+968"},
  {label:"Pakistan",flag:"🇵🇰",code:"+92"},{label:"Palau",flag:"🇵🇼",code:"+680"},{label:"Palestine",flag:"🇵🇸",code:"+970"},{label:"Panama",flag:"🇵🇦",code:"+507"},{label:"Papua New Guinea",flag:"🇵🇬",code:"+675"},{label:"Paraguay",flag:"🇵🇾",code:"+595"},{label:"Peru",flag:"🇵🇪",code:"+51"},{label:"Philippines",flag:"🇵🇭",code:"+63"},{label:"Pitcairn Islands",flag:"🇵🇳",code:"+64"},{label:"Poland",flag:"🇵🇱",code:"+48"},{label:"Portugal",flag:"🇵🇹",code:"+351"},{label:"Puerto Rico",flag:"🇵🇷",code:"+1787"},{label:"Puerto Rico",flag:"🇵🇷",code:"+1939"},
  {label:"Qatar",flag:"🇶🇦",code:"+974"},
  {label:"Réunion",flag:"🇷🇪",code:"+262"},{label:"Romania",flag:"🇷🇴",code:"+40"},{label:"Russia",flag:"🇷🇺",code:"+7"},{label:"Rwanda",flag:"🇷🇼",code:"+250"},
  {label:"Saint Barthélemy",flag:"🇧🇱",code:"+590"},{label:"Saint Helena",flag:"🇸🇭",code:"+290"},{label:"Saint Kitts and Nevis",flag:"🇰🇳",code:"+1869"},{label:"Saint Lucia",flag:"🇱🇨",code:"+1758"},{label:"Saint Martin",flag:"🇲🇫",code:"+590"},{label:"Saint Pierre and Miquelon",flag:"🇵🇲",code:"+508"},{label:"Saint Vincent and the Grenadines",flag:"🇻🇨",code:"+1784"},{label:"Samoa",flag:"🇼🇸",code:"+685"},{label:"San Marino",flag:"🇸🇲",code:"+378"},{label:"São Tomé and Príncipe",flag:"🇸🇹",code:"+239"},{label:"Saudi Arabia",flag:"🇸🇦",code:"+966"},{label:"Senegal",flag:"🇸🇳",code:"+221"},{label:"Serbia",flag:"🇷🇸",code:"+381"},{label:"Seychelles",flag:"🇸🇨",code:"+248"},{label:"Sierra Leone",flag:"🇸🇱",code:"+232"},{label:"Singapore",flag:"🇸🇬",code:"+65"},{label:"Sint Maarten",flag:"🇸🇽",code:"+1721"},{label:"Slovakia",flag:"🇸🇰",code:"+421"},{label:"Slovenia",flag:"🇸🇮",code:"+386"},{label:"Solomon Islands",flag:"🇸🇧",code:"+677"},{label:"Somalia",flag:"🇸🇴",code:"+252"},{label:"South Africa",flag:"🇿🇦",code:"+27"},{label:"South Korea",flag:"🇰🇷",code:"+82"},{label:"South Sudan",flag:"🇸🇸",code:"+211"},{label:"Spain",flag:"🇪🇸",code:"+34"},{label:"Sri Lanka",flag:"🇱🇰",code:"+94"},{label:"Sudan",flag:"🇸🇩",code:"+249"},{label:"Suriname",flag:"🇸🇷",code:"+597"},{label:"Svalbard and Jan Mayen",flag:"🇸🇯",code:"+47"},{label:"Sweden",flag:"🇸🇪",code:"+46"},{label:"Switzerland",flag:"🇨🇭",code:"+41"},{label:"Syria",flag:"🇸🇾",code:"+963"},
  {label:"Taiwan",flag:"🇹🇼",code:"+886"},{label:"Tajikistan",flag:"🇹🇯",code:"+992"},{label:"Tanzania",flag:"🇹🇿",code:"+255"},{label:"Thailand",flag:"🇹🇭",code:"+66"},{label:"Timor-Leste",flag:"🇹🇱",code:"+670"},{label:"Togo",flag:"🇹🇬",code:"+228"},{label:"Tokelau",flag:"🇹🇰",code:"+690"},{label:"Tonga",flag:"🇹🇴",code:"+676"},{label:"Trinidad and Tobago",flag:"🇹🇹",code:"+1868"},{label:"Tunisia",flag:"🇹🇳",code:"+216"},{label:"Türkiye",flag:"🇹🇷",code:"+90"},{label:"Turkmenistan",flag:"🇹🇲",code:"+993"},{label:"Turks and Caicos Islands",flag:"🇹🇨",code:"+1649"},{label:"Tuvalu",flag:"🇹🇻",code:"+688"},
  {label:"U.S. Virgin Islands",flag:"🇻🇮",code:"+1340"},{label:"Uganda",flag:"🇺🇬",code:"+256"},{label:"Ukraine",flag:"🇺🇦",code:"+380"},{label:"United Arab Emirates",flag:"🇦🇪",code:"+971"},{label:"United Kingdom",flag:"🇬🇧",code:"+44"},{label:"United States",flag:"🇺🇸",code:"+1"},{label:"Uruguay",flag:"🇺🇾",code:"+598"},{label:"Uzbekistan",flag:"🇺🇿",code:"+998"},
  {label:"Vanuatu",flag:"🇻🇺",code:"+678"},{label:"Vatican City",flag:"🇻🇦",code:"+39"},{label:"Venezuela",flag:"🇻🇪",code:"+58"},{label:"Vietnam",flag:"🇻🇳",code:"+84"},
  {label:"Wallis and Futuna",flag:"🇼🇫",code:"+681"},{label:"Western Sahara",flag:"🇪🇭",code:"+212"},{label:"Yemen",flag:"🇾🇪",code:"+967"},{label:"Zambia",flag:"🇿🇲",code:"+260"},{label:"Zimbabwe",flag:"🇿🇼",code:"+263"},
];
