export type Product = "Meitu" | "BeautyCam" | "Wink";
export type Application = { id:string; creatorId?:string; name:string; handle:string; city:string; province?:string; category:string; product:Product; followers:string; status:string; score:number; submitted:string; avatar:string; email?:string; whatsapp?:string; dateOfBirth?:string; tiktokUrl?:string; instagramUrl?:string; threadsUrl?:string; tiktokFollowers?:string; instagramFollowers?:string; threadsFollowers?:string; interestedApps?:string; featuresUsed?:string; motivation?:string; impressions?:string; declineReason?:string; reviewedAt?:string; reviewedBy?:string; reviewedByName?:string };
export type Task = { id:string; title:string; product:Product; platform:string; deadline:string; joined:number; budget:number; status:string; progress:number; cover:string; niches?:string; brief?:string; referenceLink?:string; tutorialLink?:string; startsAt?:string };
export type Submission = { id:string; creatorId?:string; campaignId?:string; creator:string; task:string; product:Product; platform:string; views:number; aiViews:number; totalEngagement?:number; analyticsStatus?:string; analyticsError?:string; analyticsModel?:string; analyticsProcessedAt?:string; analyticsAttemptCount?:number; recommendation:string; confidence:number; status:string; submitted:string; avatar:string; postUrl?:string; publishedAt?:string; boostCode?:string; evidenceKey?:string; evidenceName?:string; engagementRate?:number; whatsapp?:string; submittedAt?:string; qualificationReason?:string };
export type Reward = { id:string; creatorId?:string; campaignId?:string; creator:string; task:string; product:Product; views:number; type:string; amount:number; status:string; submissionId?:string; paymentFormChecked?:number; paidAt?:string; failureReason?:string; vipCode?:string };
export type CreatorTask = { id:string; creator:string; taskId:string; joinedAt:string; status:string };
export type AppExpansionRequest = { id:string; creatorId?:string; creator:string; currentApps:string; requestedApps:string; reason:string; status:string; submitted:string; declineReason?:string };
export type StreakRequest = { id:string; creatorId?:string; creator:string; completedTasks:number; selectedApp:Product; status:string; vipCode?:string; submitted:string; reviewedAt?:string; startTaskCount?:number; startedAt?:string };
export type PaymentForm = { id:string; product:Product; month:string; url:string; updatedAt?:string };
export type CreatorProfile = { id:string; creator:string; niches:string; displayName?:string; contactEmail?:string; avatarKey?:string; avatarName?:string; tiktokUrl?:string; instagramUrl?:string; threadsUrl?:string; whatsapp?:string; updatedAt?:string };

export const fmtIdr = (value:number) => new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(value);
export const fmtNum = (value:number) => new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:1}).format(value);
