"use client";

import { createContext, useContext, useEffect, useState } from "react";

export type PortalLanguage = "id" | "en";

type LanguageContextValue = {
  language: PortalLanguage;
  setLanguage: (language: PortalLanguage) => void;
};

const STORAGE_KEY = "creator-pool-language";
const LanguageContext = createContext<LanguageContextValue | null>(null);

const copyPairs: ReadonlyArray<readonly [english: string, indonesian: string]> = [
  ["Overview", "Ringkasan"],
  ["Applications", "Pendaftaran"],
  ["Creators", "Kreator"],
  ["Campaigns", "Kampanye"],
  ["Submissions", "Kiriman"],
  ["Rewards", "Hadiah"],
  ["Payment Forms", "Formulir Pembayaran"],
  ["Campaign Completion Streak", "Rangkaian Penyelesaian Kampanye"],
  ["Reports", "Laporan"],
  ["Home", "Beranda"],
  ["Leaderboard", "Papan Peringkat"],
  ["Profile", "Profil"],
  ["Settings", "Pengaturan"],
  ["Team", "Tim"],
  ["Creator", "Kreator"],
  ["Workspace", "Ruang kerja"],
  ["Creator space", "Ruang kreator"],
  ["Public site", "Situs publik"],
  ["Apply New Apps", "Daftar Aplikasi Baru"],
  ["Priority creator", "Kreator prioritas"],
  ["Create campaign", "Buat kampanye"],
  ["Create a post", "Buat kiriman"],
  ["Open menu", "Buka menu"],
  ["Close menu", "Tutup menu"],
  ["Notifications", "Notifikasi"],
  ["Account", "Akun"],
  ["Creator account", "Akun kreator"],
  ["Team administrator", "Administrator tim"],
  ["Open team profile menu", "Buka menu profil tim"],
  ["Close team profile menu", "Tutup menu profil tim"],
  ["Close profile menu", "Tutup menu profil"],
  ["Team profile", "Profil tim"],
  ["Creator Pool administrator · Indonesia", "Administrator Creator Pool · Indonesia"],
  ["Administrator", "Administrator"],
  ["Role", "Peran"],
  ["Workspace", "Ruang kerja"],
  ["Log out", "Keluar"],
  ["Close team profile", "Tutup profil tim"],
  ["Language", "Bahasa"],
  ["Bahasa Indonesia", "Bahasa Indonesia"],
  ["250M+ Global Users", "250 Juta+ Pengguna Global"],
  ["Top 1 in Google Play & App Store Rankings", "Peringkat 1 di Google Play & App Store"],
  ["Global brand ecosystem", "Ekosistem merek global"],
  ["Continuous creator growth support", "Dukungan pertumbuhan kreator berkelanjutan"],
  ["Meitu global highlights", "Sorotan global Meitu"],

  ["Accepted", "Diterima"],
  ["Declined", "Ditolak"],
  ["In review", "Sedang ditinjau"],
  ["Draft", "Draf"],
  ["Qualified", "Memenuhi Syarat"],
  ["Approved", "Disetujui"],
  ["Not Qualified", "Tidak Memenuhi Syarat"],
  ["Revision requested", "Revisi diminta"],
  ["Payment Info Required", "Informasi Pembayaran Diperlukan"],
  ["On Hold", "Ditahan"],
  ["Ongoing", "Berlangsung"],
  ["Expired", "Berakhir"],
  ["Active", "Aktif"],
  ["Pending", "Menunggu"],
  ["AI screening", "Penyaringan AI"],
  ["Draft saved", "Draf tersimpan"],
  ["Just now", "Baru saja"],
  ["Yesterday", "Kemarin"],
  ["Today", "Hari ini"],
  ["Processing", "Sedang diproses"],
  ["Pending AI extraction", "Menunggu ekstraksi AI"],
  ["AI extracted", "Diekstrak AI"],

  ["Beauty", "Kecantikan"],
  ["Fashion", "Fashion"],
  ["Food F&B", "Kuliner"],
  ["Travel & Nature", "Travel & Alam"],
  ["Lifestyle", "Lifestyle"],
  ["Comedy & Skits", "Komedi & Hiburan"],
  ["JJ & Trends", "JJ & Tren"],
  ["Commentary / Storytelling", "Komentar / Bercerita"],
  ["Family / Couple", "Keluarga / Pasangan"],
  ["Education / Motivational", "Edukasi / Motivasi"],
  ["Tech & Gadgets", "Teknologi & Gadget"],
  ["Gaming", "Game"],
  ["Kpop / Dance / Concert", "Kpop / Tari / Konser"],
  ["Editing / Photography", "Editing / Fotografi"],
  ["Followers", "Pengikut"],
  ["Cash", "Tunai"],
  ["Followers not provided", "Jumlah pengikut belum diisi"],
  ["No social accounts provided", "Belum ada akun media sosial"],
  ["No WhatsApp", "Tidak ada WhatsApp"],

  ["Wednesday, 5 August", "Rabu, 5 Agustus"],
  ["Good morning, Alya", "Selamat pagi, Alya"],
  ["Here’s what needs attention across Creator Pool today.", "Berikut hal yang perlu diperhatikan di Creator Pool hari ini."],
  ["Last 30 days⌄", "30 hari terakhir⌄"],
  ["View reports ↗", "Lihat laporan ↗"],
  ["Applications to review", "Pendaftaran untuk ditinjau"],
  ["Total creators", "Total kreator"],
  ["Open applications", "Buka pendaftaran"],
  ["Open creators", "Buka kreator"],
  ["Open submissions", "Buka kiriman"],
  ["Team overview shortcuts", "Pintasan ringkasan tim"],
  ["Here’s your Creator Pool performance overview.", "Berikut ringkasan performa Creator Pool Anda."],
  ["↑ 12% this week", "↑ 12% minggu ini"],
  ["Active creators", "Kreator aktif"],
  ["+16 this month", "+16 bulan ini"],
  ["Submissions in queue", "Kiriman dalam antrean"],
  ["4 high confidence", "4 berkeyakinan tinggi"],
  ["Hours saved", "Jam yang dihemat"],
  ["↑ 21% vs last month", "↑ 21% dibanding bulan lalu"],
  ["Creator activity", "Aktivitas kreator"],
  ["Qualified submissions across products", "Kiriman yang memenuhi syarat di semua produk"],
  ["Real-time submissions across products", "Kiriman real-time di semua produk"],
  ["Needs attention", "Perlu perhatian"],
  ["Prioritized by urgency", "Diurutkan berdasarkan urgensi"],
  ["View all", "Lihat semua"],
  ["Submissions awaiting review", "Kiriman menunggu tinjauan"],
  ["Revisions due within 48h", "Revisi jatuh tempo dalam 48 jam"],
  ["2 due today", "2 jatuh tempo hari ini"],
  ["Rewards awaiting approval", "Hadiah menunggu persetujuan"],
  ["IDR 8.25M total", "Total Rp8,25 juta"],
  ["AI checks need verification", "Pemeriksaan AI perlu verifikasi"],
  ["Low confidence", "Keyakinan rendah"],
  ["Submission review queue", "Antrean tinjauan kiriman"],
  ["AI recommendations require a human decision", "Rekomendasi AI memerlukan keputusan manusia"],
  ["View all submissions →", "Lihat semua kiriman →"],
  ["Campaign", "Kampanye"],
  ["Product", "Produk"],
  ["Verified views", "Tayangan terverifikasi"],
  ["AI recommendation", "Rekomendasi AI"],
  ["Confidence", "Tingkat keyakinan"],
  ["Status", "Status"],
  ["Mismatch flagged", "Ketidaksesuaian ditandai"],
  ["Evidence matched", "Bukti sesuai"],
  ["Approve", "Setujui"],
  ["Revision", "Revisi"],

  ["Creator applications", "Pendaftaran kreator"],
  ["Review new-app access requests from existing creators.", "Tinjau permintaan akses aplikasi baru dari kreator yang sudah terdaftar."],
  ["Review creator applications and app-access requests with a fully manual Team decision.", "Tinjau pendaftaran kreator dan permintaan akses aplikasi dengan keputusan manual sepenuhnya oleh Tim."],
  ["MANUAL REVIEW", "TINJAUAN MANUAL"],
  ["Every application is reviewed by your Team", "Setiap pendaftaran ditinjau oleh Tim Anda"],
  ["Check creator details, social accounts, and written answers before accepting or declining.", "Periksa detail kreator, akun sosial, dan jawaban tertulis sebelum menerima atau menolak."],
  ["creator applications awaiting review", "pendaftaran kreator menunggu tinjauan"],
  ["Creator applications only", "Hanya pendaftaran kreator"],
  ["Waiting for a Team decision", "Menunggu keputusan Tim"],
  ["Added to the creator pool", "Ditambahkan ke creator pool"],
  ["Decision sent to creator", "Keputusan dikirim kepada kreator"],
  ["requests", "permintaan"],
  ["Social Media", "Media Sosial"],
  ["Current apps", "Aplikasi saat ini"],
  ["Requested apps", "Aplikasi yang diminta"],
  ["Requested app", "Aplikasi yang diminta"],
  ["Oldest first", "Terlama lebih dulu"],
  ["View Request", "Lihat Permintaan"],
  ["No matching app requests", "Tidak ada permintaan aplikasi yang sesuai"],
  ["Try another search, app, or status.", "Coba pencarian, aplikasi, atau status lain."],
  ["App access request", "Permintaan akses aplikasi"],
  ["Why do you want to join these apps?", "Mengapa Anda ingin bergabung dengan aplikasi ini?"],
  ["Edit decision", "Edit keputusan"],
  ["Undo", "Batalkan"],
  ["Decision", "Keputusan"],
  ["Change the decision or move this application back into the review queue.", "Ubah keputusan atau pindahkan pendaftaran ini kembali ke antrean tinjauan."],
  ["Decision history", "Riwayat keputusan"],
  ["The latest saved decision replaces the current status. Use “In review” to undo the previous action.", "Keputusan terbaru yang disimpan menggantikan status saat ini. Gunakan “Sedang ditinjau” untuk membatalkan tindakan sebelumnya."],
  ["Save decision", "Simpan keputusan"],
  ["Close decision editor", "Tutup editor keputusan"],
  ["Decline", "Tolak"],
  ["Approve access", "Setujui akses"],
  ["No new app requests", "Tidak ada permintaan aplikasi baru"],
  ["Requests submitted by creators will appear here.", "Permintaan yang dikirim kreator akan muncul di sini."],
  ["Total Applications", "Total Pendaftaran"],
  ["Pending Review", "Menunggu Tinjauan"],
  ["↑ 12% vs last 30 days", "↑ 12% dibanding 30 hari terakhir"],
  ["↓ 8% vs last 30 days", "↓ 8% dibanding 30 hari terakhir"],
  ["↑ 15% vs last 30 days", "↑ 15% dibanding 30 hari terakhir"],
  ["↓ 5% vs last 30 days", "↓ 5% dibanding 30 hari terakhir"],
  ["Review new creator applications and manage your creator pool.", "Tinjau pendaftaran kreator baru dan kelola kumpulan kreator Anda."],
  ["⇧ Export", "⇧ Ekspor"],
  ["＋ Invite creator", "＋ Undang kreator"],
  ["Auto-approve creators meeting AI Auto-Accept criteria", "Setujui otomatis kreator yang memenuhi kriteria Penerimaan Otomatis AI"],
  ["Followers must match the declared tier, with recent posting activity or more than 100K followers.", "Jumlah pengikut harus sesuai dengan tingkat yang dinyatakan, disertai aktivitas posting terbaru atau lebih dari 100 ribu pengikut."],
  ["Search by name, email or username…", "Cari berdasarkan nama, email, atau nama pengguna…"],
  ["Application status", "Status pendaftaran"],
  ["Platforms", "Platform"],
  ["Apps", "Aplikasi"],
  ["Sort by", "Urutkan berdasarkan"],
  ["Newest first", "Terbaru lebih dulu"],
  ["Highest followers first", "Pengikut terbanyak lebih dulu"],
  ["All", "Semua"],
  ["No matching applications", "Tidak ada pendaftaran yang sesuai"],
  ["Try changing one or more filters.", "Coba ubah satu atau beberapa filter."],
  ["Contact", "Kontak"],
  ["Target Apps", "Aplikasi Tujuan"],
  ["AI Verification", "Verifikasi AI"],
  ["Submitted", "Dikirim"],
  ["Actions", "Tindakan"],
  ["✦ Auto-Accepted", "✦ Diterima Otomatis"],
  ["! Manually Check", "! Periksa Manual"],
  ["Followers tier consistent", "Tingkat pengikut sesuai"],
  ["Follower count mismatch", "Jumlah pengikut tidak sesuai"],
  ["Active in past month", "Aktif dalam sebulan terakhir"],
  ["Followers above 100K", "Pengikut di atas 100 ribu"],
  ["Recent activity not verified", "Aktivitas terbaru belum terverifikasi"],
  ["Close", "Tutup"],
  ["View Answers", "Lihat Jawaban"],
  ["Accept", "Terima"],
  ["Application answers", "Jawaban pendaftaran"],
  ["Creative profile", "Profil kreatif"],
  ["Decline reason sent to creator", "Alasan penolakan dikirim kepada kreator"],
  ["What features do you usually use on Meitu/Wink/BeautyCam to edit photos/videos?", "Fitur apa yang biasanya Anda gunakan di Meitu/Wink/BeautyCam untuk menyunting foto/video?"],
  ["No answer submitted.", "Tidak ada jawaban yang dikirim."],
  ["What makes you more interested in becoming a Meitu Creator?", "Apa yang membuat Anda tertarik menjadi Kreator Meitu?"],
  ["Any impressions, messages, or questions for Meitu and the team?", "Adakah kesan, pesan, atau pertanyaan untuk Meitu dan tim?"],
  ["Close decline dialog", "Tutup dialog penolakan"],
  ["Close VIP code dialog", "Tutup dialog kode VIP"],
  ["Close engagement editor", "Tutup editor tingkat interaksi"],
  ["Close payment failure dialog", "Tutup dialog kegagalan pembayaran"],
  ["Decline application", "Tolak pendaftaran"],
  ["The creator will receive the reason you provide below.", "Kreator akan menerima alasan yang Anda tulis di bawah ini."],
  ["Reason for declining", "Alasan penolakan"],
  ["Explain clearly why this application was not accepted…", "Jelaskan dengan jelas mengapa pendaftaran ini tidak diterima…"],
  ["This reason will be shown to the creator.", "Alasan ini akan ditampilkan kepada kreator."],
  ["Cancel", "Batal"],
  ["Decline & send reason", "Tolak & kirim alasan"],

  ["Search and curate accepted creators by app, platform, niche, followers, province, and city.", "Cari dan kelola kreator yang diterima berdasarkan aplikasi, platform, niche, pengikut, provinsi, dan kota."],
  ["CREATOR DIRECTORY", "DIREKTORI KREATOR"],
  ["creators in this view", "kreator dalam tampilan ini"],
  ["Filter the pool, review contact details, and control how many creators appear on each page.", "Saring kumpulan kreator, tinjau detail kontak, dan atur jumlah kreator yang muncul di setiap halaman."],
  ["Provinces", "Provinsi"],
  ["No creators match these filters", "Tidak ada kreator yang sesuai dengan filter ini"],
  ["Previous page", "Halaman sebelumnya"],
  ["Next page", "Halaman berikutnya"],
  ["10 / page", "10 / halaman"],
  ["25 / page", "25 / halaman"],
  ["50 / page", "50 / halaman"],
  ["100 / page", "100 / halaman"],
  ["Export list", "Ekspor daftar"],
  ["Invite creator", "Undang kreator"],
  ["Search creators", "Cari kreator"],
  ["Name or username…", "Nama atau nama pengguna…"],
  ["App", "Aplikasi"],
  ["Social platform", "Platform sosial"],
  ["Niche", "Niche"],
  ["Province", "Provinsi"],
  ["City", "Kota"],
  ["creators", "kreator"],
  ["Only accepted creators are listed", "Hanya kreator yang diterima yang ditampilkan"],
  ["Campaigns completed", "Kampanye selesai"],

  ["Campaigns for you", "Kampanye untuk Anda"],
  ["View and submit campaigns from the apps you are registered in.", "Lihat dan kirim konten untuk kampanye dari aplikasi yang Anda ikuti."],
  ["Search, preview, and manage creator campaigns.", "Cari, pratinjau, dan kelola kampanye kreator."],
  ["＋ Create campaign", "＋ Buat kampanye"],
  ["Search campaign name, ID, or app…", "Cari nama kampanye, ID, atau aplikasi…"],
  ["Search campaigns", "Cari kampanye"],
  ["Search", "Cari"],
  ["All apps", "Semua aplikasi"],
  ["Only campaigns for your registered apps", "Hanya kampanye untuk aplikasi yang Anda ikuti"],
  ["Registered apps", "Aplikasi terdaftar"],
  ["Campaigns are ordered by relevance to your niches", "Kampanye diurutkan berdasarkan kecocokan dengan niche Anda"],
  ["Campaign name", "Nama kampanye"],
  ["App name", "Nama aplikasi"],
  ["Campaign code", "Kode kampanye"],
  ["Deadline", "Batas waktu"],
  ["Submission deadline", "Batas waktu pengiriman"],
  ["View campaign", "Lihat kampanye"],
  ["View Campaign", "Lihat Kampanye"],
  ["Submission closed", "Pengiriman ditutup"],
  ["Submit your post", "Kirim postingan Anda"],
  ["Submit your Post", "Kirim Postingan Anda"],
  ["Preview", "Pratinjau"],
  ["Manage campaign", "Kelola kampanye"],
  ["Manage Campaign", "Kelola Kampanye"],
  ["No matching campaigns", "Tidak ada kampanye yang sesuai"],
  ["Try another search, app, or status filter.", "Coba pencarian, aplikasi, atau filter status lain."],

  ["My submissions", "Kiriman saya"],
  ["Track submission analytics and the Team’s final decisions.", "Pantau analitik kiriman dan keputusan akhir Tim."],
  ["Track reviews, results, and the team’s decision reasons.", "Pantau pemeriksaan, hasil, dan alasan keputusan tim."],
  ["Verify screenshots, AI-calculated analytics, reward eligibility, and make the final decision.", "Verifikasi tangkapan layar, analitik hasil perhitungan AI, kelayakan hadiah, dan buat keputusan akhir."],
  ["＋ Create a post", "＋ Buat kiriman"],
  ["Platform", "Platform"],
  ["Newest", "Terbaru"],
  ["Highest viewers", "Tayangan tertinggi"],
  ["Highest engagement", "Interaksi tertinggi"],
  ["Total posts", "Total postingan"],
  ["Current selection", "Pilihan saat ini"],
  ["Total viewers", "Total penonton"],
  ["AI-verified views", "Tayangan terverifikasi AI"],
  ["Average engagement", "Rata-rata interaksi"],
  ["AI-calculated posts", "postingan dihitung AI"],
  ["✦ AI ANALYTICS", "✦ ANALITIK AI"],
  ["Engagement rate extraction", "Ekstraksi tingkat interaksi"],
  ["AI reads the uploaded analytics screenshot, sums every visible engagement, and divides it by verified views. Creators never enter this rate manually.", "AI membaca tangkapan layar analitik yang diunggah, menjumlahkan semua interaksi yang terlihat, lalu membaginya dengan tayangan terverifikasi. Kreator tidak pernah memasukkan tingkat ini secara manual."],
  ["Total engagement ÷ Views × 100", "Total interaksi ÷ Tayangan × 100"],
  ["Likes, comments, shares, saves or total interactions shown in the screenshot.", "Suka, komentar, bagikan, simpan, atau total interaksi yang terlihat pada tangkapan layar."],
  ["Submission history", "Riwayat kiriman"],
  ["posts in this selection", "postingan dalam pilihan ini"],
  ["Campaign / product", "Kampanye / produk"],
  ["Post", "Postingan"],
  ["Analytics", "Analitik"],
  ["Decision", "Keputusan"],
  ["Open post ↗", "Buka postingan ↗"],
  ["Posted", "Diposting"],
  ["AI ENGAGEMENT", "INTERAKSI AI"],
  ["Total engagement", "Total interaksi"],
  ["Reading screenshot…", "Membaca tangkapan layar…"],
  ["View analytics screenshot ↗", "Lihat tangkapan layar analitik ↗"],
  ["No screenshot attached", "Tidak ada tangkapan layar terlampir"],
  ["Post link", "Tautan postingan"],
  ["No submissions yet", "Belum ada kiriman"],
  ["Your submitted posts will appear here.", "Postingan yang Anda kirim akan muncul di sini."],
  ["Analytics mismatch detected", "Ketidaksesuaian analitik terdeteksi"],
  ["Submitted after 7 days", "Dikirim setelah 7 hari"],
  ["View Rewards →", "Lihat Hadiah →"],
  ["Decision complete", "Keputusan selesai"],
  ["Add the creator-facing reason", "Tambahkan alasan untuk kreator"],
  ["This reason will be visible on the creator side.", "Alasan ini akan terlihat di sisi kreator."],
  ["Reason", "Alasan"],
  ["Select a reason", "Pilih alasan"],
  ["The post is submitted after seven days", "Postingan dikirim setelah tujuh hari"],
  ["The system detects abnormality in the post’s analytics", "Sistem mendeteksi ketidakwajaran pada analitik postingan"],
  ["Other", "Lainnya"],
  ["Manual notes", "Catatan manual"],
  ["Explain specifically why this submission is not qualified…", "Jelaskan secara spesifik mengapa kiriman ini tidak memenuhi syarat…"],
  ["Confirm Not Qualified", "Konfirmasi Tidak Memenuhi Syarat"],

  ["Reward", "Hadiah"],
  ["Fill in the payment form for each app and track your payment status.", "Isi formulir pembayaran sesuai aplikasi dan pantau status pembayaran Anda."],
  ["Track cash rewards, payment-form readiness, and campaign spend.", "Pantau hadiah tunai, kesiapan formulir pembayaran, dan pengeluaran kampanye."],
  ["↓ Export paid-ready", "↓ Ekspor siap bayar"],
  ["Payment process", "Proses pembayaran"],
  ["Payments are processed approximately", "Pembayaran diproses sekitar"],
  ["45 business days after the end of the video release month", "45 hari kerja setelah akhir bulan rilis video"],
  ["For example: videos posted in August are recapped on 31 August and paid around 30 September–15 October, excluding Saturdays, Sundays, and public holidays.", "Contoh: video yang diposting pada Agustus direkap 31 Agustus dan dibayar sekitar 30 September–15 Oktober, tidak termasuk Sabtu, Minggu, dan hari libur."],
  ["All payments are sent from overseas, so processing may take longer.", "Semua pembayaran dikirim dari luar negeri, sehingga prosesnya dapat membutuhkan waktu lebih lama."],
  ["Payment-form completion is tracked manually by the Team. Use the status control to adjust what the creator sees.", "Penyelesaian formulir pembayaran dilacak secara manual oleh Tim. Gunakan kontrol status untuk menyesuaikan yang dilihat kreator."],
  ["Total rewards", "Total hadiah"],
  ["qualified cash rewards", "hadiah tunai yang memenuhi syarat"],
  ["Paid", "Dibayar"],
  ["payment forms checked", "formulir pembayaran diperiksa"],
  ["Qualified viewers", "Penonton yang memenuhi syarat"],
  ["Current app/campaign selection", "Pilihan aplikasi/kampanye saat ini"],
  ["Reward history", "Riwayat hadiah"],
  ["Payment tracker", "Pelacak pembayaran"],
  ["Fill in the payment form that matches your reward app.", "Isi formulir pembayaran yang sesuai dengan aplikasi hadiah Anda."],
  ["Only qualified submissions with money rewards appear here", "Hanya kiriman yang memenuhi syarat dengan hadiah uang yang muncul di sini"],
  ["Views", "Tayangan"],
  ["Payment form", "Formulir pembayaran"],
  ["Fill payment form ↗", "Isi formulir pembayaran ↗"],
  ["Form not available yet", "Formulir belum tersedia"],
  ["Contact the Creator Pool Team", "Hubungi Tim Creator Pool"],
  ["Form received", "Formulir diterima"],
  ["Awaiting form", "Menunggu formulir"],

  ["Attach one monthly payment form for each app. Eligible creators will see the matching link in Rewards.", "Lampirkan satu formulir pembayaran bulanan untuk setiap aplikasi. Kreator yang memenuhi syarat akan melihat tautan yang sesuai di Hadiah."],
  ["Save changes", "Simpan perubahan"],
  ["Save payment forms", "Simpan formulir pembayaran"],
  ["Editing", "Mengedit"],
  ["Update any link below, then save your changes.", "Perbarui tautan di bawah, lalu simpan perubahan Anda."],
  ["Cancel edit", "Batalkan edit"],
  ["Payment period", "Periode pembayaran"],
  ["Use a new set of links every month. Previous periods remain in the history below.", "Gunakan rangkaian tautan baru setiap bulan. Periode sebelumnya tetap tersedia dalam riwayat di bawah."],
  ["Form URL", "URL formulir"],
  ["Test link ↗", "Uji tautan ↗"],
  ["No link yet", "Belum ada tautan"],
  ["Payment form history", "Riwayat formulir pembayaran"],
  ["app-period forms", "formulir periode aplikasi"],
  ["Period", "Periode"],
  ["Form link", "Tautan formulir"],
  ["Open form ↗", "Buka formulir ↗"],
  ["Link not set", "Tautan belum diatur"],
  ["Edit", "Edit"],
  ["Delete", "Hapus"],

  ["Approve creators who completed 10 campaigns and issue one free one-month VIP code.", "Setujui kreator yang menyelesaikan 10 kampanye dan terbitkan satu kode VIP gratis selama satu bulan."],
  ["streak requests", "permintaan rangkaian"],
  ["Completed campaigns", "Kampanye selesai"],
  ["VIP app choice", "Pilihan aplikasi VIP"],
  ["VIP code", "Kode VIP"],
  ["Approve & add code", "Setujui & tambahkan kode"],
  ["Edit VIP code", "Edit kode VIP"],
  ["Eligible creator claims will appear here.", "Klaim kreator yang memenuhi syarat akan muncul di sini."],
  ["Reward: Free 1-month VIP", "Hadiah: VIP gratis 1 bulan"],
  ["Save corrected code", "Simpan kode yang diperbaiki"],
  ["Approve & send code", "Setujui & kirim kode"],

  ["Generate performance reports per campaign, app, and month.", "Buat laporan performa per kampanye, aplikasi, dan bulan."],
  ["Download report", "Unduh laporan"],
  ["Month", "Bulan"],
  ["Total views", "Total tayangan"],
  ["AI-verified", "Terverifikasi AI"],
  ["Budget spent", "Anggaran terpakai"],
  ["Cash rewards", "Hadiah tunai"],
  ["AI–human agreement", "Kesesuaian AI–manusia"],
  ["Campaign breakdown", "Rincian kampanye"],
  ["Posts, viewers, spend, and agreement per campaign", "Postingan, penonton, pengeluaran, dan kesesuaian per kampanye"],
  ["Posts", "Postingan"],

  ["Keep up the good work!", "Pertahankan kerja bagusmu!"],
  ["Your momentum is getting stronger!", "Momentum kamu semakin kuat!"],
  ["Amazing — you’re on fire!", "Luar biasa — kamu sedang bersinar!"],
  ["Outstanding — top creator performance!", "Hebat — performa kreator terbaik!"],
  ["Editing tips, latest campaigns, and creator inspiration.", "Tips editing, kampanye terbaru, dan inspirasi kreator."],
  ["Portrait inspiration and trending beauty ideas.", "Inspirasi portrait dan tren kecantikan yang sedang ramai."],
  ["Video tutorials, transitions, and creator spotlights.", "Tutorial video, transisi, dan sorotan kreator."],
  ["Hi, Salsa! 👋", "Hai, Salsa! 👋"],
  ["You have 2 active campaigns and 1 submission awaiting review.", "Kamu punya 2 kampanye aktif dan 1 kiriman menunggu pemeriksaan."],
  ["Find a new campaign", "Cari kampanye baru"],
  ["PERFORMANCE THIS MONTH", "PERFORMA BULAN INI"],
  ["Next target: 5M views", "Target berikutnya: 5 juta tayangan"],
  ["POSITION", "POSISI"],
  ["Top Performers · Monthly", "Kreator Terbaik · Bulanan"],
  ["View leaderboard →", "Lihat papan peringkat →"],
  ["APPROVED REWARDS", "HADIAH DISETUJUI"],
  ["3 qualified posts", "3 konten memenuhi syarat"],
  ["View rewards →", "Lihat hadiah →"],
  ["Next steps", "Langkah berikutnya"],
  ["Your priorities today", "Prioritas untukmu hari ini"],
  ["Creator summary", "Ringkasan kreator"],
  ["NEXT STEPS", "LANGKAH BERIKUTNYA"],
  ["Previous suggestion", "Saran sebelumnya"],
  ["Next suggestion", "Saran berikutnya"],
  ["Suggestion", "Saran"],
  ["Next-step suggestions", "Saran langkah berikutnya"],
  ["Choose suggestion", "Pilih saran"],
  ["Swipe up for next suggestion", "Usap ke atas untuk saran berikutnya"],
  ["PRIORITY", "PRIORITAS"],
  ["CAMPAIGN GOAL", "TARGET KAMPANYE"],
  ["Goal: free 1-month VIP", "Target: VIP gratis 1 bulan"],
  ["Update BeautyCam post data", "Perbarui data posting BeautyCam"],
  ["Ends tomorrow, 18:00 WIB", "Berakhir besok, 18.00 WIB"],
  ["Fix now →", "Perbaiki sekarang →"],
  ["Submit Summer Glow Retouch", "Kirim Summer Glow Retouch"],
  ["Deadline 12 August", "Batas waktu 12 Agustus"],
  ["Create a post →", "Buat kiriman →"],
  ["Motion Magic reward approved", "Hadiah Motion Magic disetujui"],
  ["Fill in the payment form for the app", "Isi formulir pembayaran sesuai aplikasinya"],
  ["View details →", "Lihat detail →"],
  ["Congrats! You received a free 1-month VIP code for one app of your choice.", "Selamat! Kamu mendapatkan kode VIP gratis 1 bulan untuk 1 aplikasi pilihanmu."],
  ["Choose app", "Pilih aplikasi"],
  ["Claim 1-month VIP", "Klaim VIP 1 bulan"],
  ["Your VIP code", "Kode VIP kamu"],
  ["Start New Streak", "Mulai Rangkaian Baru"],
  ["New streak started", "Rangkaian baru dimulai"],
  ["VIP Code History", "Riwayat Kode VIP"],
  ["STAY INSPIRED", "TERUS TERINSPIRASI"],
  ["Follow us on social media", "Ikuti kami di media sosial"],
  ["Follow the official Meitu, BeautyCam, and Wink accounts for the latest trends, tutorials, and content inspiration.", "Ikuti akun resmi Meitu, BeautyCam, dan Wink untuk tren terbaru, tutorial, dan inspirasi konten berikutnya."],
  ["OFFICIAL ACCOUNT", "AKUN RESMI"],
  ["Close VIP Code History", "Tutup Riwayat Kode VIP"],
  ["Your previously received free VIP codes.", "Daftar Kode VIP gratis yang sebelumnya sudah kamu terima."],
  ["Received", "Diterima"],
  ["1-month VIP", "VIP 1 bulan"],
  ["No VIP Codes yet", "Belum ada Kode VIP"],
  ["Approved VIP Codes will be saved here.", "Kode VIP yang sudah disetujui akan tersimpan di sini."],
  ["Done", "Selesai"],

  ["CAMPAIGN JOURNEY", "PERJALANAN KAMPANYE"],
  ["Campaign Collaboration Flow", "Alur Kolaborasi Kampanye"],
  ["From campaign details to rewards in five simple steps.", "Dari detail kampanye hingga hadiah dalam lima langkah sederhana."],
  ["View campaign details", "Lihat detail kampanye"],
  ["Review the brief, deadline, and campaign links.", "Pelajari brief, tenggat waktu, dan tautan kampanye."],
  ["Create and publish", "Buat dan publikasikan"],
  ["Create content for your selected social channel.", "Buat konten untuk kanal sosial yang kamu pilih."],
  ["Submit within 7 days", "Kirim dalam 7 hari"],
  ["Send your public post link before the review window closes.", "Kirim tautan postingan publik sebelum periode peninjauan berakhir."],
  ["Team evaluation", "Evaluasi Tim"],
  ["The Meitu Team checks your post against the campaign brief.", "Tim Meitu memeriksa kesesuaian postingan dengan brief kampanye."],
  ["Fill form & earn rewards", "Isi formulir & dapatkan hadiah"],
  ["Qualified posts unlock the payment form and rewards.", "Postingan yang memenuhi syarat membuka formulir pembayaran dan hadiah."],
  ["FILTER SUBMISSIONS", "SARING KIRIMAN"],

  ["Top Monthly Viewers", "Penonton Bulanan Teratas"],
  ["Top Gainers", "Peraih Hadiah Teratas"],
  ["All-time leaders ranked by the total cash rewards they have earned.", "Peringkat sepanjang masa berdasarkan total hadiah tunai yang diperoleh."],
  ["Filter by app", "Saring berdasarkan aplikasi"],
  ["Filter by campaign", "Saring berdasarkan kampanye"],
  ["All campaigns", "Semua kampanye"],
  ["Monthly period", "Periode bulanan"],
  ["eligible creators", "kreator yang memenuhi syarat"],
  ["creators submitted for this campaign", "kreator mengirim untuk kampanye ini"],
  ["Rank & creator", "Peringkat & kreator"],
  ["Qualified performance", "Performa yang memenuhi syarat"],
  ["All-time rewards", "Hadiah sepanjang masa"],
  ["Winning posts", "Postingan pemenang"],
  ["post unavailable", "postingan tidak tersedia"],
  ["No public post link", "Tidak ada tautan postingan publik"],
  ["qualified post", "postingan memenuhi syarat"],
  ["qualified posts", "postingan memenuhi syarat"],
  ["No qualified posts found", "Tidak ditemukan postingan yang memenuhi syarat"],
  ["Try a different app or campaign filter.", "Coba filter aplikasi atau kampanye lain."],
  ["all-time reward", "hadiah sepanjang masa"],
  ["entry", "entri"],
  ["entries", "entri"],
  ["No reward history yet", "Belum ada riwayat hadiah"],
  ["Approved creator rewards will appear here.", "Hadiah kreator yang disetujui akan muncul di sini."],
  ["Monthly leaders", "Pemimpin bulanan"],
  ["All-time gainers", "Peraih sepanjang masa"],
  ["Top creators", "Kreator teratas"],
  ["Top three creators", "Tiga kreator teratas"],

  ["Creator profile", "Profil kreator"],
  ["Manage your contact details, public social links, and campaign matching preferences.", "Kelola detail kontak, tautan sosial publik, dan preferensi pencocokan kampanye Anda."],
  ["Update your public identity and social accounts.", "Perbarui identitas publik dan akun sosialmu."],
  ["Priority", "Prioritas"],
  ["Account status", "Status akun"],
  ["Joined", "Bergabung"],
  ["Location", "Lokasi"],
  ["Public information", "Informasi publik"],
  ["Display name", "Nama tampilan"],
  ["Contact email", "Email kontak"],
  ["Your public name", "Nama publik Anda"],
  ["Social & Channel Links", "Tautan Sosial & Kanal"],
  ["Select one or more platforms. Each selected platform needs a public channel or profile URL.", "Pilih satu atau beberapa platform. Setiap platform yang dipilih memerlukan URL kanal atau profil publik."],
  ["Choose up to three niches to improve campaign matching.", "Pilih hingga tiga niche untuk meningkatkan pencocokan kampanye."],
  ["niches selected", "niche dipilih"],
  ["The Team uses this number only for Creator Pool communication.", "Tim hanya menggunakan nomor ini untuk komunikasi Creator Pool."],
  ["Display name is required.", "Nama tampilan wajib diisi."],
  ["Enter a valid contact email.", "Masukkan email kontak yang valid."],
  ["Select at least one social platform.", "Pilih setidaknya satu platform sosial."],
  ["Select at least one niche.", "Pilih setidaknya satu niche."],
  ["Enter a 7–13 digit WhatsApp number without a leading zero.", "Masukkan nomor WhatsApp 7–13 digit tanpa angka nol di depan."],
  ["Profile changes could not be saved.", "Perubahan profil tidak dapat disimpan."],
  ["A beauty creator who loves practical tutorials and natural transformations.", "Kreator kecantikan yang suka membuat tutorial praktis dan transformasi natural."],
  ["Save changes", "Simpan perubahan"],
  ["Set your niche, social links, and WhatsApp number so the Team can contact you.", "Atur niche, tautan sosial, dan nomor WhatsApp yang bisa dihubungi Tim."],
  ["Choose at least one niche.", "Pilih minimal satu niche."],
  ["Enter a local WhatsApp number with 7–13 digits without a leading zero.", "Masukkan nomor WhatsApp lokal dengan 7–13 digit tanpa angka 0 di depan."],
  ["Do not include a leading zero.", "Jangan masukkan angka 0 di depan."],
  ["Your settings could not be saved.", "Pengaturan belum berhasil disimpan."],
  ["Your niches", "Niche kamu"],
  ["These niches are used to order campaign recommendations. Choose up to 3.", "Niche ini digunakan untuk mengurutkan rekomendasi kampanye. Pilih maksimal 3."],
  ["CONTACT", "KONTAK"],
  ["WhatsApp number", "Nomor WhatsApp"],
  ["The number is saved in international format so the Team can open WhatsApp directly.", "Nomor disimpan dalam format internasional agar Tim dapat membuka WhatsApp secara langsung."],
  ["Country code", "Kode negara"],
  ["Saving…", "Menyimpan…"],
  ["Save settings", "Simpan pengaturan"],

  ["Close review", "Tutup tinjauan"],
  ["Human review required", "Tinjauan manusia diperlukan"],
  ["verified views", "tayangan terverifikasi"],
  ["AI recommends", "AI merekomendasikan"],
  ["The post URL, boostcode, and video analytics evidence are complete and consistent with the submitted performance data.", "URL postingan, boostcode, dan bukti analitik video lengkap serta konsisten dengan data performa yang dikirim."],
  ["The submission is relevant, but one requirement needs human verification before a final decision.", "Kiriman relevan, tetapi satu persyaratan perlu diverifikasi manusia sebelum keputusan akhir."],
  ["Post URL accessible", "URL postingan dapat diakses"],
  ["Boostcode provided", "Boostcode tersedia"],
  ["Video analytics attached", "Analitik video terlampir"],
  ["View data complete", "Data tayangan lengkap"],
  ["AI is advisory only. You retain final decision authority.", "AI hanya memberikan saran. Anda tetap memiliki kewenangan atas keputusan akhir."],
  ["Video analytics screenshot", "Bukti tangkapan layar analitik video"],
  ["Analytics screenshot", "Tangkapan layar analitik"],
  ["Open full-size image ↗", "Buka gambar ukuran penuh ↗"],
  ["Legacy submission", "Kiriman lama"],
  ["No screenshot is stored for this older submission.", "Belum ada tangkapan layar tersimpan untuk kiriman lama."],
  ["Post details", "Detail postingan"],
  ["Post URL", "URL postingan"],
  ["Open post ↗", "Buka postingan ↗"],
  ["Publication date", "Tanggal publikasi"],
  ["Analytics verification", "Verifikasi analitik"],
  ["Declared views tier", "Tingkat tayangan yang dinyatakan"],
  ["AI extracted views", "Tayangan hasil ekstraksi AI"],
  ["Engagement rate", "Tingkat interaksi"],
  ["Internal note", "Catatan internal"],
  ["Add context for the audit log…", "Tambahkan konteks untuk catatan audit…"],
  ["↻ Request revision", "↻ Minta revisi"],
  ["✓ Approve submission", "✓ Setujui kiriman"],

  ["New campaign", "Kampanye baru"],
  ["Edit campaign", "Edit kampanye"],
  ["Create a creator campaign", "Buat kampanye kreator"],
  ["Set the brief resources and deadline. Creators may submit repeatedly until the deadline.", "Atur materi brief dan batas waktu. Kreator dapat mengirim berulang kali hingga batas waktu."],
  ["Campaign title", "Judul kampanye"],
  ["e.g. Eid Portrait Refresh", "mis. Penyegaran Potret Idulfitri"],
  ["Creator-facing brief", "Brief untuk kreator"],
  ["Describe the creative objective and the result creators should show…", "Jelaskan tujuan kreatif dan hasil yang perlu ditampilkan kreator…"],
  ["Reference link", "Tautan referensi"],
  ["How to access feature / tutorial link", "Tautan cara mengakses fitur / tutorial"],
  ["Which KOL niches fit this brief?", "Brief ini cocok untuk niche KOL apa?"],
  ["Choose as many as needed", "Pilih sebanyak yang dibutuhkan"],
  ["Clear all", "Hapus semua"],
  ["Select all", "Pilih semua"],
  ["Campaign starts", "Kampanye dimulai"],
  ["Reward eligibility rule", "Aturan kelayakan hadiah"],
  ["Content must be submitted no later than 7 days after posting. There is no campaign budget cap, and creators may submit consecutively until the campaign deadline.", "Konten harus dikirim paling lambat 7 hari setelah diposting. Tidak ada batas anggaran kampanye, dan kreator dapat mengirim berturut-turut hingga batas waktu kampanye."],
  ["AI campaign matching", "Pencocokan kampanye AI"],
  ["AI compares the campaign niches with each creator profile and ranks the best-fit briefs from top to bottom.", "AI membandingkan niche kampanye dengan profil setiap kreator dan mengurutkan brief yang paling sesuai dari atas ke bawah."],
  ["Publish campaign", "Terbitkan kampanye"],
  ["Review the complete campaign information before creating your post.", "Tinjau informasi kampanye lengkap sebelum membuat postingan Anda."],
  ["Live campaign details and submission performance.", "Detail kampanye aktif dan performa kiriman."],
  ["Creators submitted", "Kreator yang mengirim"],
  ["Posts submitted", "Postingan terkirim"],
  ["Qualified posts", "Postingan memenuhi syarat"],
  ["Campaign period", "Periode kampanye"],
  ["Brief description", "Deskripsi brief"],
  ["No brief description provided.", "Belum ada deskripsi brief."],
  ["Open reference link ↗", "Buka tautan referensi ↗"],
  ["Open feature tutorial ↗", "Buka tutorial fitur ↗"],

  ["Creator access", "Akses kreator"],
  ["Apply for access to other apps to receive relevant campaigns after approval.", "Ajukan akses ke aplikasi lain untuk mendapatkan kampanye yang relevan setelah disetujui."],
  ["Apps you already joined", "Aplikasi yang sudah kamu ikuti"],
  ["Choose new apps", "Pilih aplikasi baru"],
  ["Under review", "Sedang ditinjau"],
  ["✓ Selected", "✓ Dipilih"],
  ["Choose app", "Pilih aplikasi"],
  ["All apps are active", "Semua aplikasi sudah aktif"],
  ["You are already registered in Meitu, BeautyCam, and Wink.", "Kamu sudah terdaftar di Meitu, BeautyCam, dan Wink."],
  ["Why do you want to join?", "Mengapa kamu ingin bergabung?"],
  ["Tell us about the content and campaign ideas you want to create…", "Ceritakan jenis konten dan ide kampanye yang ingin kamu buat…"],
  ["Application under review", "Pengajuan sedang ditinjau"],
  ["Campaigns for new apps will appear after the Creator Pool Team approves your application.", "Kampanye untuk aplikasi baru akan muncul setelah Tim Creator Pool menyetujui pengajuanmu."],
  ["Submit application", "Kirim pengajuan"],

  ["Upload a screenshot of the post analytics before sending for verification.", "Unggah tangkapan layar analitik postingan sebelum dikirim untuk verifikasi."],
  ["The analytics screenshot could not be uploaded.", "Tangkapan layar analitik tidak berhasil diunggah."],
  ["The submission could not be saved.", "Kiriman tidak berhasil disimpan."],
  ["No ongoing campaigns available", "Tidak ada kampanye yang sedang berlangsung"],
  ["You can submit after a campaign for one of your registered apps becomes active.", "Anda dapat mengirim setelah kampanye untuk salah satu aplikasi terdaftar menjadi aktif."],
  ["Your campaign list is currently closed", "Daftar kampanye Anda saat ini ditutup"],
  ["Open Campaigns to review available briefs and deadlines.", "Buka Kampanye untuk meninjau brief dan batas waktu yang tersedia."],
  ["Complete the post details. The campaign selected from the Campaigns list is preselected for you.", "Lengkapi detail postingan. Kampanye yang dipilih dari daftar Kampanye telah dipilih otomatis untuk Anda."],
  ["Selected campaign", "Kampanye terpilih"],
  ["Post platform", "Platform postingan"],
  ["Post link", "Tautan postingan"],
  ["Posting date", "Tanggal posting"],
  ["Choose the category shown in your analytics screenshot.", "Pilih kategori yang terlihat pada tangkapan layar analitik Anda."],
  ["Submit without Reward", "Kirim tanpa Hadiah"],
  ["1 Month VIP", "VIP 1 Bulan"],
  ["Your selected viewer category determines the reward tier shown here.", "Kategori penonton yang dipilih menentukan tingkat hadiah yang ditampilkan di sini."],
  ["AI analytics verification", "Verifikasi analitik AI"],
  ["Upload the post analytics screenshot. Meitu’s system will verify its authenticity and use it to calculate the post’s engagement rate.", "Unggah tangkapan layar analitik postingan. Sistem Meitu akan memverifikasi keasliannya dan menggunakannya untuk menghitung tingkat interaksi postingan."],
  ["Spark Ads code", "Kode Spark Ads"],
  ["Required for TikTok or Instagram posts with at least 10.000 views.", "Wajib untuk postingan TikTok atau Instagram dengan minimal 10.000 tayangan."],
  ["How to get a boostcode ↗", "Cara mendapatkan boostcode ↗"],
  ["No boostcode required", "Boostcode tidak diperlukan"],
  ["Threads posts do not use boostcodes or Spark Ads codes.", "Postingan Threads tidak menggunakan boostcode atau kode Spark Ads."],
  ["Posts below 10.000 views do not need a boostcode.", "Postingan di bawah 10.000 tayangan tidak memerlukan boostcode."],
  ["Boostcode tutorial ↗", "Tutorial boostcode ↗"],
  ["Post analytics screenshot", "Tangkapan layar analitik postingan"],
  ["Choose an analytics screenshot", "Pilih tangkapan layar analitik"],
  ["JPG, PNG, or WEBP · maximum 8 MB", "JPG, PNG, atau WEBP · maksimum 8 MB"],
  ["Submit no later than 7 days after posting", "Kirim paling lambat 7 hari setelah posting"],
  ["Submissions received after seven days may be marked Not Qualified. Meitu will verify the authenticity of the analytics before confirming any reward.", "Kiriman yang diterima setelah tujuh hari dapat ditandai Tidak Memenuhi Syarat. Meitu akan memverifikasi keaslian analitik sebelum mengonfirmasi hadiah."],
  ["Save as draft", "Simpan sebagai draf"],
  ["Uploading analytics…", "Mengunggah analitik…"],
  ["Send for verification", "Kirim untuk verifikasi"],

  ["About Meitu", "Tentang Meitu"],
  ["How To Register", "Cara Daftar"],
  ["Sign in", "Masuk"],
  ["Register now", "Daftar sekarang"],
  ["Welcome to", "Selamat datang di"],
  ["Turn your creativity into real opportunities with Meitu, BeautyCam, and Wink.", "Wujudkan kreativitasmu menjadi peluang nyata bersama Meitu, BeautyCam, dan Wink."],
  ["Join Creator Pool Now!", "Gabung Creator Pool Sekarang!"],
  ["At Meitu, we believe technology can help everyone express and present the best version of themselves through photos, videos, and every shared moment.", "Di Meitu, kami percaya bahwa teknologi dapat membantu setiap orang mengekspresikan dan menghadirkan versi terbaik dari diri mereka melalui foto, video, dan setiap momen yang dibagikan."],
  ["Since 2008, Meitu has continued to innovate and transform how people capture, enhance, and share stories through innovative photo and video editing technology.", "Sejak tahun 2008, Meitu terus berinovasi untuk mengubah cara pengguna mengabadikan, menyempurnakan, dan membagikan cerita melalui teknologi pengeditan foto dan video inovatif."],
  ["With more than 250 million users worldwide, Meitu combines AI innovation with a practical and easy experience.", "Dengan lebih dari 250 juta pengguna di seluruh dunia, Meitu memadukan inovasi AI dengan pengalaman yang praktis dan mudah."],
  ["Meitu headquarters", "Kantor pusat Meitu"],
  ["MEITU INDONESIA CREATOR PROGRAM", "PROGRAM KREATOR MEITU INDONESIA"],
  ["What is", "Apa itu"],
  ["An exclusive Meitu Indonesia program where creators promote in-app features, earn rewards, and access special collaboration opportunities and benefits for active, loyal creators.", "Program eksklusif dari Meitu Indonesia sebagai wadah kreator untuk berkreasi mempromosikan fitur dalam aplikasi, dengan sistem hadiah serta kesempatan kolaborasi dan manfaat spesial bagi kreator yang aktif dan loyal."],
  ["Meitu, BeautyCam, and Wink creator community", "Komunitas kreator Meitu, BeautyCam, dan Wink"],
  ["Cash Reward", "Hadiah Tunai"],
  ["You have a chance to win cash rewards.", "Kamu berkesempatan memenangkan hadiah uang tunai."],
  ["Boost Your Exposure", "Tingkatkan Jangkauanmu"],
  ["Get advertising support and opportunities to become an official model in Meitu apps.", "Dapatkan dukungan iklan dan peluang menjadi model resmi di aplikasi Meitu."],
  ["Long Term Collaboration", "Kolaborasi Jangka Panjang"],
  ["Consistent performance opens opportunities for higher rates and exclusive projects.", "Performa konsisten membuka peluang tarif yang lebih tinggi dan proyek eksklusif."],
  ["Build Your Portfolio", "Bangun Portofoliomu"],
  ["Work with global brands to strengthen your positioning as a content creator.", "Bekerja dengan merek global untuk memperkuat posisi sebagai kreator konten."],
  ["JOINING PROCESS", "PROSES BERGABUNG"],
  ["How Do You", "Bagaimana Cara"],
  ["Become a Creator?", "Menjadi Kreator?"],
  ["Join the Meitu Creator Pool and turn your creativity into real opportunities!", "Yuk, bergabung menjadi bagian dari Meitu Creator Pool dan wujudkan kreativitasmu menjadi peluang nyata!"],
  ["Your creativity can", "Kreativitasmu bisa"],
  ["inspire millions of people", "menginspirasi jutaan orang"],
  ["and open many opportunities with", "dan membuka banyak peluang bersama"],
  ["Creator Reward Tier", "Tingkat Hadiah Kreator"],
  ["The higher the views, the bigger the reward!", "Semakin tinggi tayangan, semakin besar hadiahnya!"],
  ["Tier", "Tingkat"],
  ["Keep creating, earn rewards, and realize your potential with Meitu!", "Terus berkarya, raih hadiah, dan wujudkan potensimu bersama Meitu!"],
  ["Ready to Become a", "Siap Menjadi"],
  ["Meitu Creator?", "Kreator Meitu?"],
  ["A place where creativity meets opportunity.", "Tempat kreativitas bertemu peluang."],
  ["Terms & Support", "Ketentuan & Dukungan"],
  ["Creator Portal", "Portal Kreator"],

  ["Register Yourself", "Daftarkan Dirimu"],
  ["Fill in the registration form and complete your details. The Meitu Team will select creators based on fit.", "Isi formulir pendaftaran dan lengkapi data dirimu. Tim Meitu akan menyeleksi berdasarkan kecocokan."],
  ["Join the Exclusive Group", "Bergabung ke Grup Eksklusif"],
  ["Selected creators will be invited to a special group for the latest campaign information and briefs.", "Kreator terpilih akan diundang ke grup khusus untuk mendapatkan informasi kampanye dan brief terbaru."],
  ["Receive the Brief & Start Posting", "Terima Brief & Mulai Posting"],
  ["Follow the Meitu Team’s brief, then create content in your own style within the timeline.", "Ikuti brief dari Tim Meitu, lalu buat konten dengan gaya kreatifmu sesuai jadwal."],
  ["Submit Link & Earn Rewards", "Kirim Tautan & Dapatkan Hadiah"],
  ["Submit the published content link for review and rewards.", "Kirim tautan konten yang sudah tayang untuk proses tinjauan dan hadiah."],
  ["Opportunity to Become a Meitu KOL", "Kesempatan Menjadi KOL Meitu"],
  ["Consistent performance unlocks campaign priority and exclusive collaborations.", "Performa konsisten membuka prioritas kampanye dan kolaborasi eksklusif."],
  ["Create standout photo edits with iconic AI tools.", "Buat editan foto menonjol dengan alat AI unggulan."],
  ["Turn every portrait into polished, creator-ready content.", "Ubah setiap potret menjadi konten yang rapi dan siap dibagikan kreator."],
  ["Bring short-form video stories to life with smarter editing.", "Hidupkan cerita video pendek dengan penyuntingan yang lebih cerdas."],

  ["Creator registration", "Pendaftaran kreator"],
  ["Step", "Langkah"],
  ["of 3", "dari 3"],
  ["Personal details", "Data diri"],
  ["Apps & social accounts", "Aplikasi & akun sosial"],
  ["Creative profile", "Profil kreatif"],
  ["We use your email to send the Creator Hub invitation.", "Kami menggunakan email untuk mengirim undangan Creator Hub."],
  ["Choose products and share the accounts you want to use.", "Pilih produk dan bagikan akun yang ingin kamu gunakan."],
  ["Tell us about your experience and complete the registration.", "Ceritakan pengalamanmu dan selesaikan pendaftaran."],
  ["Full name", "Nama lengkap"],
  ["Name as shown on your ID", "Nama sesuai identitas"],
  ["The Creator Hub invitation will be sent to this address.", "Undangan Creator Hub akan dikirim ke alamat ini."],
  ["WhatsApp number", "Nomor WhatsApp"],
  ["Choose province", "Pilih provinsi"],
  ["Choose city", "Pilih kota"],
  ["Choose a province first", "Pilih provinsi terlebih dahulu"],
  ["Date of birth", "Tanggal lahir"],
  ["Applicants must be at least 18 years old.", "Pendaftar harus berusia minimal 18 tahun."],
  ["Primary language", "Bahasa utama"],
  ["WhatsApp country code", "Kode negara WhatsApp"],
  ["Apps you are interested in", "Aplikasi yang kamu minati"],
  ["Choose one or more", "Pilih satu atau lebih"],
  ["Optional if another social account is provided", "Opsional jika akun sosial lain diisi"],
  ["TikTok profile link", "Tautan profil TikTok"],
  ["TikTok follower category", "Kategori pengikut TikTok"],
  ["Choose category", "Pilih kategori"],
  ["Instagram profile link", "Tautan profil Instagram"],
  ["Instagram follower category", "Kategori pengikut Instagram"],
  ["Threads profile link", "Tautan profil Threads"],
  ["Threads follower category", "Kategori pengikut Threads"],
  ["Main category", "Kategori utama"],
  ["Choose 1–3 categories", "Pilih 1–3 kategori"],
  ["For example: AI Retouch, Remove Background, Video Enhancer, portrait filters…", "Contoh: AI Retouch, Remove Background, Video Enhancer, filter potret…"],
  ["Describe the features that best match your content style and audience.", "Jelaskan fitur yang paling cocok dengan gaya konten dan audiensmu."],
  ["What makes you more interested in becoming a Meitu Creator? (Select as many as you like)", "Apa yang membuat kamu lebih tertarik menjadi Kreator Meitu? (Pilih sebanyak yang kamu inginkan)"],
  ["Any impressions, messages, or questions for Meitu and the team?", "Adakah kesan, pesan, atau pertanyaan untuk Meitu dan tim?"],
  ["Share anything you would like the Meitu team to know…", "Sampaikan hal apa pun yang ingin kamu bagikan kepada Tim Meitu…"],
  ["Read Terms & Conditions", "Baca Syarat & Ketentuan"],
  ["Please read the complete document before submitting the form.", "Mohon baca dokumen lengkap sebelum mengirim formulir."],
  ["Open Terms & Conditions ↗", "Buka Syarat & Ketentuan ↗"],
  ["I have read and agree to the Terms & Conditions and the processing of personal data.", "Saya telah membaca dan menyetujui Syarat & Ketentuan serta pemrosesan data pribadi."],
  ["Back", "Kembali"],
  ["Continue →", "Lanjut →"],
  ["Submit registration", "Kirim pendaftaran"],

  ["View", "Lihat"],
  ["STATUS", "STATUS"],
  ["Review creator applications, app-access requests, and Streak VIP Code claims in one consistent workspace.", "Tinjau pendaftaran kreator, permintaan akses aplikasi, dan klaim Kode VIP Rangkaian dalam satu ruang kerja yang konsisten."],
  ["Pending out of total", "Menunggu dari total"],
  ["Accepted out of total", "Diterima dari total"],
  ["Declined out of total", "Ditolak dari total"],
  ["Search and curate accepted creators by platform, niche, followers, and city.", "Cari dan kelola kreator yang diterima berdasarkan platform, niche, pengikut, dan kota."],
  ["Filter by niche", "Saring berdasarkan niche"],
  ["Select one or more. Creators matching any selected niche will appear.", "Pilih satu atau beberapa. Kreator yang sesuai dengan salah satu niche pilihan akan ditampilkan."],
  ["All niches", "Semua niche"],
  ["Search campaign name or app…", "Cari nama kampanye atau aplikasi…"],
  ["Review AI-verified analytics and record the final qualification decision.", "Tinjau analitik yang telah diverifikasi AI dan catat keputusan kualifikasi akhir."],
  ["Read from creator analytics", "Dibaca dari analitik kreator"],
  ["AI-analyzed posts", "postingan yang dianalisis AI"],
  ["Awaiting review", "Menunggu tinjauan"],
  ["Needs a Team decision", "Memerlukan keputusan Tim"],
  ["Public post", "Postingan publik"],
  ["Edit rate", "Edit tingkat"],
  ["Awaiting Form", "Menunggu Formulir"],
  ["Payment-form completion and reward status are tracked independently, so changing one will not overwrite the other.", "Penyelesaian formulir pembayaran dan status hadiah dilacak secara terpisah, sehingga perubahan pada salah satunya tidak akan menimpa yang lain."],
  ["Please Fill In Payment Form", "Silakan Isi Formulir Pembayaran"],
  ["In Payment", "Dalam Proses Pembayaran"],
  ["Fully Paid", "Dibayar Penuh"],
  ["Pay Fail", "Pembayaran Gagal"],
  ["Review manually qualified performance per campaign, app, and month.", "Tinjau performa yang memenuhi syarat secara manual berdasarkan kampanye, aplikasi, dan bulan."],
  ["Qualified views", "Tayangan yang memenuhi syarat"],
  ["Manual decisions", "Keputusan manual"],
  ["Posts, qualified views, manual decisions, and spend per campaign", "Postingan, tayangan yang memenuhi syarat, keputusan manual, dan pengeluaran per kampanye"],
  ["Campaigns submitted", "Kampanye yang dikirim"],
  ["Open your submitted campaigns", "Buka kampanye yang telah dikirim"],
  ["View the creator leaderboard", "Lihat papan peringkat kreator"],
  ["Across all submitted posts", "Dari semua postingan yang dikirim"],
  ["Total earnings", "Total pendapatan"],
  ["Open your rewards", "Buka hadiah Anda"],
  ["Creator performance summary", "Ringkasan performa kreator"],
  ["Open creator profile menu", "Buka menu profil kreator"],
  ["Create and post", "Buat dan posting"],
  ["Create your content and publish it on the selected platform.", "Buat konten lalu publikasikan di platform yang dipilih."],
  ["Submit within 7 days after posting", "Kirim dalam 7 hari setelah posting"],
  ["Send the public post and analytics no later than seven days after it goes live.", "Kirim postingan publik dan analitik paling lambat tujuh hari setelah dipublikasikan."],
  ["Qualification check", "Pemeriksaan kualifikasi"],
  ["The Meitu system checks the qualification of your post.", "Sistem Meitu memeriksa kelayakan postingan Anda."],
  ["Complete payment & earn", "Lengkapi pembayaran & dapatkan hadiah"],
  ["If qualified, fill in the payment form and receive your reward.", "Jika memenuhi syarat, isi formulir pembayaran dan terima hadiah Anda."],
  ["Filter by app and status", "Saring berdasarkan aplikasi dan status"],
  ["qualified", "memenuhi syarat"],
  ["post", "postingan"],
  ["posts", "postingan"],
  ["of", "dari"],
  ["you@example.com", "anda@contoh.com"],
  ["Use the full portal in English", "Gunakan seluruh portal dalam bahasa Inggris"],
  ["Use the full portal in Bahasa Indonesia", "Gunakan seluruh portal dalam Bahasa Indonesia"],
  ["name@email.com", "nama@email.com"],
  ["Total paid out", "Total dibayar"],
  ["Pending payment", "Pembayaran tertunda"],
  ["Reward & payment details", "Detail hadiah & pembayaran"],
  ["Every qualified campaign and its current payment status.", "Semua kampanye yang memenuhi syarat beserta status pembayarannya saat ini."],
  ["Amount", "Jumlah"],
  ["Payment status", "Status pembayaran"],
  ["Payment summary", "Ringkasan pembayaran"],
  ["Manage your contact details, public social links, and campaign matching preferences.", "Kelola detail kontak, tautan media sosial publik, dan preferensi pencocokan kampanye Anda."],
  ["PUBLIC INFORMATION", "INFORMASI PUBLIK"],
  ["Your name and contact email are used across Creator Pool.", "Nama dan email kontak Anda digunakan di seluruh Creator Pool."],
  ["Open TikTok post ↗", "Buka postingan TikTok ↗"],
  ["Open Instagram post ↗", "Buka postingan Instagram ↗"],
  ["Open Threads post ↗", "Buka postingan Threads ↗"],
  ["Open", "Buka"],
  ["submitted", "dikirim"],
  ["Verified viewers", "Penonton terverifikasi"],
  ["Engagement", "Interaksi"],
  ["Name", "Nama"],
  ["Manual analytics correction", "Koreksi analitik manual"],
  ["Edit engagement rate", "Edit tingkat interaksi"],
  ["Use this only when the automated calculation is incorrect.", "Gunakan ini hanya jika perhitungan otomatis tidak tepat."],
  ["The saved percentage replaces the automated value and is visible to the creator.", "Persentase yang disimpan menggantikan nilai otomatis dan dapat dilihat oleh kreator."],
  ["Engagement rate (%)", "Tingkat interaksi (%)"],
  ["Save rate", "Simpan tingkat"],
  ["This manual review decision will be visible to the creator.", "Keputusan tinjauan manual ini akan terlihat oleh kreator."],
  ["The post was submitted after seven days", "Postingan dikirim setelah tujuh hari"],
  ["The analytics could not be verified", "Analitik tidak dapat diverifikasi"],
  ["The post does not meet the campaign requirements", "Postingan tidak memenuhi persyaratan kampanye"],
  ["The public post link cannot be reviewed", "Tautan postingan publik tidak dapat ditinjau"],
  ["Analytics retention", "Penyimpanan analitik"],
  ["Change this result to Qualified, Not Qualified, or move it back to In Review.", "Ubah hasil ini menjadi Memenuhi Syarat, Tidak Memenuhi Syarat, atau kembalikan ke Sedang Ditinjau."],
  ["The calculated engagement rate remains available. A previously deleted analytics image is not restored when moving back to In Review.", "Tingkat interaksi yang telah dihitung tetap tersedia. Gambar analitik yang sebelumnya dihapus tidak akan dipulihkan ketika dikembalikan ke Sedang Ditinjau."],
  ["Link unavailable", "Tautan tidak tersedia"],
];

const copyAliases: ReadonlyArray<readonly [source: string, english: string, indonesian: string]> = [
  ["Tunjukkan transformasi summer glow yang natural dan mudah diikuti audiens.", "Show a natural summer-glow transformation that is easy for the audience to follow.", "Tunjukkan transformasi summer glow yang natural dan mudah diikuti audiens."],
  ["Buat tutorial portrait studio satu sentuhan dengan hasil sebelum dan sesudah yang jelas.", "Create a one-tap portrait-studio tutorial with a clear before-and-after result.", "Buat tutorial portrait studio satu sentuhan dengan hasil sebelum dan sesudah yang jelas."],
  ["Tampilkan transformasi edit video yang satisfying dengan motion before-and-after.", "Show a satisfying video-editing transformation with a motion before-and-after.", "Tampilkan transformasi edit video yang memuaskan dengan gerakan sebelum dan sesudah."],
  ["Buat kiriman", "Create a post", "Buat kiriman"],
  ["Team settings tetap menggunakan konfigurasi workspace saat ini.", "Team settings continue to use the current workspace configuration.", "Pengaturan Tim tetap menggunakan konfigurasi ruang kerja saat ini."],
  ["Submission approved — views belum mencapai reward tier.", "Submission approved — views have not reached a reward tier.", "Kiriman disetujui — tayangan belum mencapai tingkat hadiah."],
  ["Revision request sent to creator.", "Revision request sent to creator.", "Permintaan revisi dikirim kepada kreator."],
  ["Qualified — reward non-tunai dicatat pada hasil submission.", "Qualified — the non-cash reward was recorded in the submission result.", "Memenuhi Syarat — hadiah nontunai dicatat pada hasil kiriman."],
  ["Submission dipindahkan ke Not Qualified dan alasan dikirim ke creator.", "The submission was moved to Not Qualified and the reason was sent to the creator.", "Kiriman dipindahkan ke Tidak Memenuhi Syarat dan alasannya dikirim kepada kreator."],
  ["Streak baru dimulai dari nol.", "A new streak started from zero.", "Rangkaian baru dimulai dari nol."],
  ["Pilihan VIP berhasil dikirim ke Team untuk approval.", "The VIP choice was sent to the Team for approval.", "Pilihan VIP berhasil dikirim kepada Tim untuk disetujui."],
  ["Profil berhasil diperbarui.", "Profile updated successfully.", "Profil berhasil diperbarui."],
  ["Settings creator berhasil disimpan.", "Creator settings saved successfully.", "Pengaturan kreator berhasil disimpan."],
  ["Draft kiriman berhasil disimpan.", "Submission draft saved successfully.", "Draf kiriman berhasil disimpan."],
  ["Kiriman dikirim untuk verifikasi. Pemeriksaan AI sedang berjalan.", "The submission was sent for verification. The AI review is in progress.", "Kiriman dikirim untuk verifikasi. Pemeriksaan AI sedang berlangsung."],
  ["Pengajuan aplikasi baru berhasil dikirim untuk review.", "The new app application was sent for review.", "Pengajuan aplikasi baru berhasil dikirim untuk ditinjau."],
  ["Lihat Rewards →", "View Rewards →", "Lihat Hadiah →"],
  ["Isi payment form sesuai aplikasi dan pantau status pembayaranmu.", "Fill in the payment form for each app and track your payment status.", "Isi formulir pembayaran sesuai aplikasi dan pantau status pembayaranmu."],
  ["Isi form pembayaran yang sesuai dengan aplikasi reward-mu.", "Fill in the payment form that matches your reward app.", "Isi formulir pembayaran yang sesuai dengan aplikasi hadiahmu."],
  ["Isi payment form ↗", "Fill payment form ↗", "Isi formulir pembayaran ↗"],
  ["Form belum tersedia", "Form not available yet", "Formulir belum tersedia"],
  ["Hubungi Team Creator Pool", "Contact the Creator Pool Team", "Hubungi Tim Creator Pool"],
  ["Approve & add code", "Approve & add code", "Setujui & tambahkan kode"],
  ["campaigns completed", "campaigns completed", "kampanye selesai"],
  ["Reward: VIP gratis 1 bulan", "Reward: Free 1-month VIP", "Hadiah: VIP gratis 1 bulan"],
  ["Amazing — kamu sedang on fire!", "Amazing — you’re on fire!", "Luar biasa — kamu sedang bersinar!"],
  ["Tips editing, campaign terbaru, dan inspirasi kreator.", "Editing tips, latest campaigns, and creator inspiration.", "Tips penyuntingan, kampanye terbaru, dan inspirasi kreator."],
  ["Portrait inspiration dan tren beauty yang lagi ramai.", "Portrait inspiration and trending beauty ideas.", "Inspirasi potret dan tren kecantikan yang sedang ramai."],
  ["Tutorial video, transitions, dan creator spotlights.", "Video tutorials, transitions, and creator spotlights.", "Tutorial video, transisi, dan sorotan kreator."],
  ["Kamu punya 2 campaign aktif dan 1 kiriman menunggu pemeriksaan.", "You have 2 active campaigns and 1 submission awaiting review.", "Kamu punya 2 kampanye aktif dan 1 kiriman menunggu pemeriksaan."],
  ["Cari campaign baru", "Find a new campaign", "Cari kampanye baru"],
  ["Target berikutnya: 5M views", "Next target: 5M views", "Target berikutnya: 5 juta tayangan"],
  ["Top Performers · Bulanan", "Top Performers · Monthly", "Kreator Terbaik · Bulanan"],
  ["Lihat leaderboard →", "View leaderboard →", "Lihat papan peringkat →"],
  ["Isi payment form sesuai aplikasinya", "Fill in the payment form for the app", "Isi formulir pembayaran sesuai aplikasinya"],
  ["Congrats! Kamu mendapatkan kode VIP gratis 1 bulan untuk 1 app pilihanmu.", "Congrats! You received a free 1-month VIP code for one app of your choice.", "Selamat! Kamu mendapatkan kode VIP gratis 1 bulan untuk 1 aplikasi pilihanmu."],
  ["Pilih app", "Choose app", "Pilih aplikasi"],
  ["VIP code kamu", "Your VIP code", "Kode VIP kamu"],
  ["Streak baru dimulai", "New streak started", "Rangkaian baru dimulai"],
  ["Tutup VIP Code History", "Close VIP Code History", "Tutup Riwayat Kode VIP"],
  ["Daftar VIP Code gratis yang sebelumnya sudah kamu terima.", "Your previously received free VIP codes.", "Daftar Kode VIP gratis yang sebelumnya sudah kamu terima."],
  ["· VIP 1 bulan", "· 1-month VIP", "· VIP 1 bulan"],
  ["Belum ada VIP Code", "No VIP Codes yet", "Belum ada Kode VIP"],
  ["VIP Code yang sudah disetujui akan tersimpan di sini.", "Approved VIP Codes will be saved here.", "Kode VIP yang sudah disetujui akan tersimpan di sini."],
  ["Profil kreator", "Creator profile", "Profil kreator"],
  ["Perbarui identitas publik dan akun sosialmu.", "Update your public identity and social accounts.", "Perbarui identitas publik dan akun sosialmu."],
  ["Informasi publik", "Public information", "Informasi publik"],
  ["Nama tampilan", "Display name", "Nama tampilan"],
  ["Beauty creator yang suka membuat tutorial praktis dan transformasi natural.", "A beauty creator who loves practical tutorials and natural transformations.", "Kreator kecantikan yang suka membuat tutorial praktis dan transformasi natural."],
  ["Atur niche, foto profil, dan nomor WhatsApp yang bisa dihubungi Team.", "Set your niche, profile photo, and WhatsApp number so the Team can contact you.", "Atur niche, foto profil, dan nomor WhatsApp yang bisa dihubungi Tim."],
  ["Settings belum berhasil disimpan.", "Your settings could not be saved.", "Pengaturan belum berhasil disimpan."],
  ["Niche ini digunakan untuk mengurutkan rekomendasi campaign. Pilih maksimal 3.", "These niches are used to order campaign recommendations. Choose up to 3.", "Niche ini digunakan untuk mengurutkan rekomendasi kampanye. Pilih maksimal 3."],
  ["Nomor disimpan dalam format internasional agar Team dapat membuka WhatsApp secara langsung.", "The number is saved in international format so the Team can open WhatsApp directly.", "Nomor disimpan dalam format internasional agar Tim dapat membuka WhatsApp secara langsung."],
  ["Simpan settings", "Save settings", "Simpan pengaturan"],
  ["Bukti screenshot analitik video", "Video analytics screenshot", "Bukti tangkapan layar analitik video"],
  ["Screenshot analitik", "Analytics screenshot", "Tangkapan layar analitik"],
  ["Belum ada screenshot tersimpan untuk kiriman lama.", "No screenshot is stored for this older submission.", "Belum ada tangkapan layar tersimpan untuk kiriman lama."],
  ["Detail posting", "Post details", "Detail postingan"],
  ["Pilih minimal satu niche KOL untuk rekomendasi campaign.", "Choose at least one KOL niche for campaign recommendations.", "Pilih minimal satu niche KOL untuk rekomendasi kampanye."],
  ["Ajukan akses ke aplikasi lain untuk mendapatkan campaign yang relevan setelah disetujui.", "Apply for access to other apps to receive relevant campaigns after approval.", "Ajukan akses ke aplikasi lain untuk mendapatkan kampanye yang relevan setelah disetujui."],
  ["Sedang direview", "Under review", "Sedang ditinjau"],
  ["Kenapa kamu ingin bergabung?", "Why do you want to join?", "Mengapa kamu ingin bergabung?"],
  ["Ceritakan jenis konten dan ide campaign yang ingin kamu buat…", "Tell us about the content and campaign ideas you want to create…", "Ceritakan jenis konten dan ide kampanye yang ingin kamu buat…"],
  ["Campaign untuk aplikasi baru akan muncul setelah Tim Creator Pool menyetujui pengajuanmu.", "Campaigns for new apps will appear after the Creator Pool Team approves your application.", "Kampanye untuk aplikasi baru akan muncul setelah Tim Creator Pool menyetujui pengajuanmu."],
  ["Isi form pendaftaran dan lengkapi data dirimu. Tim Meitu akan seleksi berdasarkan kecocokan.", "Fill in the registration form and complete your details. The Meitu Team will select creators based on fit.", "Isi formulir pendaftaran dan lengkapi data dirimu. Tim Meitu akan menyeleksi berdasarkan kecocokan."],
  ["Join Grup Eksklusif", "Join the Exclusive Group", "Bergabung ke Grup Eksklusif"],
  ["Kreator terpilih akan diundang ke grup khusus untuk mendapatkan info campaign dan brief terbaru.", "Selected creators will be invited to a special group for the latest campaign information and briefs.", "Kreator terpilih akan diundang ke grup khusus untuk mendapatkan informasi kampanye dan brief terbaru."],
  ["Ikuti brief dari tim Meitu, lalu buat konten dengan gaya kreatifmu sesuai timeline.", "Follow the Meitu Team’s brief, then create content in your own style within the timeline.", "Ikuti brief dari Tim Meitu, lalu buat konten dengan gaya kreatifmu sesuai jadwal."],
  ["Submit Link & Dapatkan Reward", "Submit Link & Earn Rewards", "Kirim Tautan & Dapatkan Hadiah"],
  ["Kirim link konten yang sudah tayang untuk proses review dan reward.", "Submit the published content link for review and rewards.", "Kirim tautan konten yang sudah tayang untuk proses tinjauan dan hadiah."],
  ["Kesempatan Jadi KOL Meitu", "Opportunity to Become a Meitu KOL", "Kesempatan Menjadi KOL Meitu"],
  ["Performa konsisten membuka prioritas campaign dan kolaborasi eksklusif.", "Consistent performance unlocks campaign priority and exclusive collaborations.", "Performa konsisten membuka prioritas kampanye dan kolaborasi eksklusif."],
  ["Tentang", "About", "Tentang"],
  ["Program eksklusif dari Meitu Indonesia sebagai wadah kreator untuk berkreasi mempromosikan fitur dalam aplikasi, dengan sistem reward serta kesempatan kolaborasi dan benefit spesial bagi kreator yang aktif dan loyal.", "An exclusive Meitu Indonesia program where creators promote in-app features, earn rewards, and access special collaboration opportunities and benefits for active, loyal creators.", "Program eksklusif dari Meitu Indonesia sebagai wadah kreator untuk mempromosikan fitur dalam aplikasi, dengan sistem hadiah serta kesempatan kolaborasi dan manfaat spesial bagi kreator yang aktif dan loyal."],
  ["Dapatkan dukungan ads dan peluang menjadi model resmi di aplikasi Meitu.", "Get advertising support and opportunities to become an official model in Meitu apps.", "Dapatkan dukungan iklan dan peluang menjadi model resmi di aplikasi Meitu."],
  ["Long Term Collab", "Long Term Collaboration", "Kolaborasi Jangka Panjang"],
  ["Performa konsisten membuka peluang rate naik dan project eksklusif.", "Consistent performance opens opportunities for higher rates and exclusive projects.", "Performa konsisten membuka peluang tarif yang lebih tinggi dan proyek eksklusif."],
  ["Bekerja dengan brand global untuk memperkuat positioning sebagai content creator.", "Work with global brands to strengthen your positioning as a content creator.", "Bekerja dengan merek global untuk memperkuat posisi sebagai kreator konten."],
  ["Gimana Cara", "How Do You", "Bagaimana Cara"],
  ["Jadi Creator?", "Become a Creator?", "Menjadi Kreator?"],
  ["Semakin tinggi views, semakin besar reward-nya!", "The higher the views, the bigger the reward!", "Semakin tinggi tayangan, semakin besar hadiahnya!"],
  ["💡 Semangat berkarya, raih reward, dan wujudkan potensimu bersama Meitu!", "💡 Keep creating, earn rewards, and realize your potential with Meitu!", "💡 Terus berkarya, raih hadiah, dan wujudkan potensimu bersama Meitu!"],
  ["Siap Jadi", "Ready to Become a", "Siap Menjadi"],
  ["Join Creator Pool Sekarang!", "Join Creator Pool Now!", "Gabung Creator Pool Sekarang!"],
  ["Pendaftaran berhasil dikirim. Kami akan mengabari statusnya.", "Registration submitted successfully. We will notify you of its status.", "Pendaftaran berhasil dikirim. Kami akan mengabari statusnya."],
  ["Karena saya sangat menyukai dan sering menggunakan Meitu / BeautyCam / Wink", "Because I really like and frequently use Meitu / BeautyCam / Wink", "Karena saya sangat menyukai dan sering menggunakan Meitu / BeautyCam / Wink"],
  ["Ingin mendapatkan reward tunai dari performa konten yang saya buat", "Want to earn cash rewards for the performance of the content I create", "Ingin mendapatkan hadiah tunai dari performa konten yang saya buat"],
  ["Ingin meningkatkan exposure akun saya", "Want to increase my account exposure", "Ingin meningkatkan jangkauan akun saya"],
  ["Ingin menjadi model resmi di ketiga aplikasi Meitu", "Want to become an official model in the three Meitu apps", "Ingin menjadi model resmi di ketiga aplikasi Meitu"],
  ["Tertarik dengan peluang kolaborasi jangka panjang", "Interested in long-term collaboration opportunities", "Tertarik dengan peluang kolaborasi jangka panjang"],
  ["Ingin mengembangkan kemampuan sebagai content creator dan belajar membuat konten berperforma tinggi", "Want to develop your skills as a content creator and learn how to create high-performing content", "Ingin mengembangkan kemampuan sebagai kreator konten dan belajar membuat konten berperforma tinggi"],
  ["Ingin membangun portofolio dengan berkolaborasi bersama brand global seperti Meitu", "Want to build a portfolio by collaborating with global brands like Meitu", "Ingin membangun portofolio dengan berkolaborasi bersama merek global seperti Meitu"],
  ["Kamu dapat memilih maksimal 3 kategori utama.", "You can choose up to 3 main categories.", "Kamu dapat memilih maksimal 3 kategori utama."],
  ["Lengkapi data diri, pilih provinsi dan kota, gunakan email valid, isi nomor WhatsApp tanpa angka 0 di depan, serta pastikan usia minimal 18 tahun.", "Complete your personal details, choose a province and city, use a valid email, enter WhatsApp without a leading zero, and make sure you are at least 18.", "Lengkapi data diri, pilih provinsi dan kota, gunakan email yang valid, isi nomor WhatsApp tanpa angka 0 di depan, serta pastikan usia minimal 18 tahun."],
  ["Pilih minimal satu aplikasi, isi minimal satu link sosial yang valid, dan pilih kategori followers untuk setiap akun yang diisi.", "Choose at least one app, provide at least one valid social link, and select a follower category for every account provided.", "Pilih minimal satu aplikasi, isi minimal satu tautan sosial yang valid, dan pilih kategori pengikut untuk setiap akun yang diisi."],
  ["Pilih minimal satu kategori dan alasan, jawab pertanyaan fitur, lalu setujui Terms & Conditions.", "Select at least one category and reason, answer the feature question, and accept the Terms & Conditions.", "Pilih minimal satu kategori dan alasan, jawab pertanyaan fitur, lalu setujui Syarat & Ketentuan."],
  ["Pendaftaran kreator · Langkah", "Creator registration · Step", "Pendaftaran kreator · Langkah"],
  ["Link profil TikTok", "TikTok profile link", "Tautan profil TikTok"],
  ["Kategori followers TikTok", "TikTok follower category", "Kategori pengikut TikTok"],
  ["Link profil Instagram", "Instagram profile link", "Tautan profil Instagram"],
  ["Kategori followers Instagram", "Instagram follower category", "Kategori pengikut Instagram"],
  ["Link profil Threads", "Threads profile link", "Tautan profil Threads"],
  ["Kategori followers Threads", "Threads follower category", "Kategori pengikut Threads"],
  ["Pilih 1–3 kategori (", "Choose 1–3 categories (", "Pilih 1–3 kategori ("],
  ["Fitur apa yang biasanya kamu gunakan di Meitu/Wink/BeautyCam untuk mengedit foto/video?", "What features do you usually use on Meitu/Wink/BeautyCam to edit photos/videos?", "Fitur apa yang biasanya kamu gunakan di Meitu/Wink/BeautyCam untuk menyunting foto/video?"],
  ["Contoh: AI Retouch, Remove Background, Video Enhancer, filter portrait…", "For example: AI Retouch, Remove Background, Video Enhancer, portrait filters…", "Contoh: AI Retouch, Remove Background, Video Enhancer, filter potret…"],
  ["Apa yang membuat kamu lebih tertarik menjadi Meitu Creator? (Pilih sebanyak yang kamu inginkan)", "What makes you more interested in becoming a Meitu Creator? (Select as many as you like)", "Apa yang membuat kamu lebih tertarik menjadi Kreator Meitu? (Pilih sebanyak yang kamu inginkan)"],
  ["Sampaikan hal apa pun yang ingin kamu bagikan kepada tim Meitu…", "Share anything you would like the Meitu team to know…", "Sampaikan hal apa pun yang ingin kamu bagikan kepada Tim Meitu…"],
  ["Baca Terms & Conditions", "Read Terms & Conditions", "Baca Syarat & Ketentuan"],
  ["Buka Terms & Conditions ↗", "Open Terms & Conditions ↗", "Buka Syarat & Ketentuan ↗"],
  ["Saya telah membaca dan menyetujui Terms & Conditions serta pemrosesan data pribadi.", "I have read and agree to the Terms & Conditions and the processing of personal data.", "Saya telah membaca dan menyetujui Syarat & Ketentuan serta pemrosesan data pribadi."],
  [", kami percaya bahwa teknologi dapat membantu setiap orang mengekspresikan dan menghadirkan versi terbaik dari diri mereka melalui foto, video, dan setiap momen yang dibagikan.", ", we believe technology can help everyone express and present the best version of themselves through photos, videos, and every shared moment.", ", kami percaya bahwa teknologi dapat membantu setiap orang mengekspresikan dan menghadirkan versi terbaik dari diri mereka melalui foto, video, dan setiap momen yang dibagikan."],
  ["Yuk, bergabung jadi bagian dari", "Join the", "Yuk, bergabung menjadi bagian dari"],
  ["dan wujudkan kreativitasmu jadi peluang nyata!", "and turn your creativity into real opportunities!", "dan wujudkan kreativitasmu menjadi peluang nyata!"],
  ["dan buka banyak peluang bersama", "and open many opportunities with", "dan membuka banyak peluang bersama"],
  ["CREATOR APP", "CREATOR APP", "APLIKASI KREATOR"],
  ["CREATOR REWARD TIER", "CREATOR REWARD TIER", "TINGKAT HADIAH KREATOR"],
  ["Portal Creator", "Creator Portal", "Portal Kreator"],
  ["CreatorHub home", "CreatorHub home", "Beranda CreatorHub"],
  ["Submit tanpa Reward", "Submit without Reward", "Kirim tanpa Hadiah"],
  ["1 Juta Views", "1 Million Views", "1 Juta Tayangan"],
  ["Pilih minimal satu aplikasi baru.", "Choose at least one new app.", "Pilih minimal satu aplikasi baru."],
  ["Jelaskan alasan kamu ingin bergabung dengan aplikasi tersebut.", "Explain why you want to join the selected app.", "Jelaskan alasan kamu ingin bergabung dengan aplikasi tersebut."],
  ["Creator apps", "Creator apps", "Aplikasi kreator"],
  ["Country code WhatsApp", "WhatsApp country code", "Kode negara WhatsApp"],
  ["total engagement ÷", "total engagement ÷", "total interaksi ÷"],
  ["views × 100", "views × 100", "tayangan × 100"],
];

const englishToIndonesian = new Map(copyPairs);
const indonesianToEnglish = new Map(copyPairs.map(([english, indonesian]) => [indonesian, english]));
const aliasToEnglish = new Map(copyAliases.map(([source, english]) => [source, english]));
const aliasToIndonesian = new Map(copyAliases.map(([source, , indonesian]) => [source, indonesian]));
const textState = new WeakMap<Text, { source: string; rendered: string }>();
const attributeState = new WeakMap<Element, Map<string, { source: string; rendered: string }>>();

const monthPairs: ReadonlyArray<readonly [string, string]> = [
  ["January", "Januari"], ["February", "Februari"], ["March", "Maret"], ["April", "April"],
  ["May", "Mei"], ["June", "Juni"], ["July", "Juli"], ["August", "Agustus"],
  ["September", "September"], ["October", "Oktober"], ["November", "November"], ["December", "Desember"],
  ["Jan", "Jan"], ["Feb", "Feb"], ["Mar", "Mar"], ["Apr", "Apr"], ["May", "Mei"], ["Jun", "Jun"],
  ["Jul", "Jul"], ["Aug", "Agu"], ["Sep", "Sep"], ["Oct", "Okt"], ["Nov", "Nov"], ["Dec", "Des"],
];

function translateDynamic(value: string, language: PortalLanguage) {
  const rules: Array<[RegExp, (...matches: string[]) => string]> = language === "id" ? [
    [/^Progress (\d+) percent toward 5 million views$/, amount => `Progres ${amount} persen menuju 5 juta tayangan`],
    [/^Show suggestion (\d+)$/, number => `Tampilkan saran ${number}`],
    [/^(\d+) of 10 campaigns completed$/, count => `${count} dari 10 kampanye selesai`],
    [/^(\d+) completed$/, count => `${count} selesai`],
    [/^Open (Meitu|BeautyCam|Wink) (TikTok|Instagram|Threads) profile$/, (brand,network) => `Buka profil ${network} ${brand}`],
    [/^(.+) Views$/, amount => `${amount} Tayangan`],
    [/^(.+) Followers$/, amount => `${amount} Pengikut`],
    [/^Download (.+)$/, app => `Unduh ${app}`],
    [/^Review (.+)$/, name => `Tinjau ${name}`],
    [/^(\d+) min ago$/, amount => `${amount} menit lalu`],
    [/^(\d+)h ago$/, amount => `${amount} jam lalu`],
    [/^Today, (.+)$/, time => `Hari ini, ${time}`],
    [/^(\d+) requests$/, count => `${count} permintaan`],
    [/^(\d+) creators$/, count => `${count} kreator`],
    [/^(\d+) posts in this selection$/, count => `${count} postingan dalam pilihan ini`],
    [/^(\d+) AI-calculated posts$/, count => `${count} postingan dihitung AI`],
    [/^(\d+) qualified cash rewards$/, count => `${count} hadiah tunai yang memenuhi syarat`],
    [/^(\d+) payment forms checked$/, count => `${count} formulir pembayaran diperiksa`],
    [/^(\d+) eligible creators$/, count => `${count} kreator yang memenuhi syarat`],
    [/^(\d+) creators submitted for this campaign$/, count => `${count} kreator mengirim untuk kampanye ini`],
    [/^(\d+) qualified posts?$/, count => `${count} postingan memenuhi syarat`],
    [/^(\d+) all-time reward entries?$/, count => `${count} entri hadiah sepanjang masa`],
    [/^(\d+) other decisions$/, count => `${count} keputusan lainnya`],
    [/^(\d+) of (\d+) app-period forms$/, (count,total) => `${count} dari ${total} formulir periode aplikasi`],
    [/^Showing (\d+)–(\d+) of (\d+)$/, (from,to,total) => `Menampilkan ${from}–${to} dari ${total}`],
    [/^Pending Review: (\d+) of (\d+), (\d+)%$/, (count,total,percentage) => `Menunggu Tinjauan: ${count} dari ${total}, ${percentage}%`],
    [/^Accepted: (\d+) of (\d+), (\d+)%$/, (count,total,percentage) => `Diterima: ${count} dari ${total}, ${percentage}%`],
    [/^Declined: (\d+) of (\d+), (\d+)%$/, (count,total,percentage) => `Ditolak: ${count} dari ${total}, ${percentage}%`],
    [/^(Meitu|BeautyCam|Wink): (\d+) qualified submissions in (.+)$/, (app,count,month) => `${app}: ${count} kiriman memenuhi syarat pada ${month}`],
    [/^(.+) submissions$/, status => `${englishToIndonesian.get(status) || status} kiriman`],
    [/^Submitted (.+)$/, date => `Dikirim ${date}`],
    [/^Posted (.+)$/, date => `Diposting ${date}`],
    [/^Submission deadline: (.+)$/, date => `Batas waktu pengiriman: ${date}`],
    [/^Deadline (.+)$/, date => `Batas waktu ${date}`],
    [/^AI recommends (.+)$/, recommendation => `AI merekomendasikan ${englishToIndonesian.get(recommendation) || recommendation}`],
    [/^Confidence (.+)$/, detail => `Tingkat keyakinan ${detail}`],
    [/^(.+) verified views$/, views => `${views} tayangan terverifikasi`],
    [/^(.+) total engagement ÷ (.+) views × 100$/, (engagement, views) => `${engagement} total interaksi ÷ ${views} tayangan × 100`],
    [/^(\d+)\/3 niches selected$/, count => `${count}/3 niche dipilih`],
    [/^(.+) campaign$/, app => `Kampanye ${app}`],
    [/^Campaign preview · (.+)$/, id => `Pratinjau kampanye · ${id}`],
    [/^Manage (.+)$/, id => `Kelola ${id}`],
    [/^Decline (.+)\?$/, name => `Tolak ${name}?`],
    [/^(.+) accepted and added to Creators\.$/, name => `${name} diterima dan ditambahkan ke Kreator.`],
    [/^(.+) declined\. The reason is ready for the creator notification\.$/, name => `${name} ditolak. Alasannya siap dikirim kepada kreator.`],
    [/^(.+) access approved for (.+)\.$/, (apps, name) => `Akses ${apps} disetujui untuk ${name}.`],
    [/^New app request from (.+) declined\.$/, name => `Permintaan aplikasi baru dari ${name} ditolak.`],
    [/^Payment forms for (.+) saved and visible to eligible creators\.$/, period => `Formulir pembayaran untuk ${period} disimpan dan terlihat oleh kreator yang memenuhi syarat.`],
    [/^(.+) payment form for (.+) deleted\.$/, (app, period) => `Formulir pembayaran ${app} untuk ${period} dihapus.`],
    [/^Delete the (.+) payment form for (.+)\?$/, (app, period) => `Hapus formulir pembayaran ${app} untuk ${period}?`],
    [/^Top five creators for (.+), ranked by qualified views\. Open their winning posts for inspiration\.$/, period => `Lima kreator terbaik untuk ${period}, berdasarkan tayangan yang memenuhi syarat. Buka postingan pemenang mereka untuk inspirasi.`],
    [/^Campaign (.+) berhasil diperbarui\.$/, title => `Kampanye ${title} berhasil diperbarui.`],
    [/^Campaign (.+) berhasil dipublikasikan\.$/, title => `Kampanye ${title} berhasil diterbitkan.`],
    [/^Qualified — reward (.+) ditambahkan ke Rewards\.$/, reward => `Memenuhi Syarat — hadiah ${reward} ditambahkan ke Hadiah.`],
    [/^(\d+) payment-ready rewards exported to CSV\.$/, count => `${count} hadiah siap bayar diekspor ke CSV.`],
  ] : [
    [/^Progres (\d+) persen menuju 5 juta tayangan$/, amount => `Progress ${amount} percent toward 5 million views`],
    [/^Tampilkan saran (\d+)$/, number => `Show suggestion ${number}`],
    [/^(\d+) dari 10 kampanye selesai$/, count => `${count} of 10 campaigns completed`],
    [/^(\d+) selesai$/, count => `${count} completed`],
    [/^Buka profil (TikTok|Instagram|Threads) (Meitu|BeautyCam|Wink)$/, (network,brand) => `Open ${brand} ${network} profile`],
    [/^(.+) Tayangan$/, amount => `${amount} Views`],
    [/^(.+) Pengikut$/, amount => `${amount} Followers`],
    [/^Unduh (.+)$/, app => `Download ${app}`],
    [/^Tinjau (.+)$/, name => `Review ${name}`],
    [/^(\d+) menit lalu$/, amount => `${amount} min ago`],
    [/^(\d+) jam lalu$/, amount => `${amount}h ago`],
    [/^Hari ini, (.+)$/, time => `Today, ${time}`],
    [/^(\d+) permintaan$/, count => `${count} requests`],
    [/^(\d+) kreator$/, count => `${count} creators`],
    [/^(\d+) postingan dalam pilihan ini$/, count => `${count} posts in this selection`],
    [/^(\d+) postingan dihitung AI$/, count => `${count} AI-calculated posts`],
    [/^(\d+) hadiah tunai yang memenuhi syarat$/, count => `${count} qualified cash rewards`],
    [/^(\d+) formulir pembayaran diperiksa$/, count => `${count} payment forms checked`],
    [/^(\d+) kreator yang memenuhi syarat$/, count => `${count} eligible creators`],
    [/^(\d+) kreator mengirim untuk kampanye ini$/, count => `${count} creators submitted for this campaign`],
    [/^(\d+) postingan memenuhi syarat$/, count => `${count} qualified posts`],
    [/^(\d+) entri hadiah sepanjang masa$/, count => `${count} all-time reward entries`],
    [/^(\d+) keputusan lainnya$/, count => `${count} other decisions`],
    [/^(\d+) dari (\d+) formulir periode aplikasi$/, (count,total) => `${count} of ${total} app-period forms`],
    [/^Menampilkan (\d+)–(\d+) dari (\d+)$/, (from,to,total) => `Showing ${from}–${to} of ${total}`],
    [/^Menunggu Tinjauan: (\d+) dari (\d+), (\d+)%$/, (count,total,percentage) => `Pending Review: ${count} of ${total}, ${percentage}%`],
    [/^Diterima: (\d+) dari (\d+), (\d+)%$/, (count,total,percentage) => `Accepted: ${count} of ${total}, ${percentage}%`],
    [/^Ditolak: (\d+) dari (\d+), (\d+)%$/, (count,total,percentage) => `Declined: ${count} of ${total}, ${percentage}%`],
    [/^(Meitu|BeautyCam|Wink): (\d+) kiriman memenuhi syarat pada (.+)$/, (app,count,month) => `${app}: ${count} qualified submissions in ${month}`],
    [/^Kota (.+)$/, city => city],
    [/^Dikirim (.+)$/, date => `Submitted ${date}`],
    [/^Diposting (.+)$/, date => `Posted ${date}`],
    [/^Batas waktu pengiriman: (.+)$/, date => `Submission deadline: ${date}`],
    [/^Batas waktu (.+)$/, date => `Deadline ${date}`],
    [/^AI merekomendasikan (.+)$/, recommendation => `AI recommends ${indonesianToEnglish.get(recommendation) || recommendation}`],
    [/^Tingkat keyakinan (.+)$/, detail => `Confidence ${detail}`],
    [/^(.+) tayangan terverifikasi$/, views => `${views} verified views`],
    [/^(.+) total interaksi ÷ (.+) tayangan × 100$/, (engagement, views) => `${engagement} total engagement ÷ ${views} views × 100`],
    [/^(\d+)\/3 niche dipilih$/, count => `${count}/3 niches selected`],
    [/^Kampanye (.+)$/, app => `${app} campaign`],
    [/^Pratinjau kampanye · (.+)$/, id => `Campaign preview · ${id}`],
    [/^Kelola (.+)$/, id => `Manage ${id}`],
    [/^Tolak (.+)\?$/, name => `Decline ${name}?`],
    [/^Lima kreator terbaik untuk (.+), berdasarkan tayangan yang memenuhi syarat\. Buka postingan pemenang mereka untuk inspirasi\.$/, period => `Top five creators for ${period}, ranked by qualified views. Open their winning posts for inspiration.`],
    [/^Campaign (.+) berhasil diperbarui\.$/, title => `Campaign ${title} updated successfully.`],
    [/^Campaign (.+) berhasil dipublikasikan\.$/, title => `Campaign ${title} published successfully.`],
    [/^Qualified — reward (.+) ditambahkan ke Rewards\.$/, reward => `Qualified — reward ${reward} added to Rewards.`],
  ];

  for (const [pattern, replacement] of rules) {
    const match = value.match(pattern);
    if (match) return replacement(...match.slice(1));
  }

  let translated = value;
  for (const [english, indonesian] of monthPairs) {
    const source = language === "id" ? english : indonesian;
    const target = language === "id" ? indonesian : english;
    translated = translated.replace(new RegExp(`\\b${source}\\b`, "g"), target);
  }
  return translated;
}

export function translatePortalText(source: string, language: PortalLanguage) {
  const leading = source.match(/^\s*/)?.[0] || "";
  const trailing = source.match(/\s*$/)?.[0] || "";
  const value = source.trim();
  if (!value) return source;
  const alias = language === "id" ? aliasToIndonesian.get(value) : aliasToEnglish.get(value);
  const exact = language === "id" ? englishToIndonesian.get(value) : indonesianToEnglish.get(value);
  if (alias || exact) return leading + (alias || exact) + trailing;

  const punctuated = value.match(/^([✓↻⇧↓✦＋!·]?\s*)(.*?)(\s*(?:·|:|→|↗))?$/);
  if (punctuated) {
    const [, prefix, core, suffix = ""] = punctuated;
    const translatedAlias = language === "id" ? aliasToIndonesian.get(core) : aliasToEnglish.get(core);
    const translatedCore = language === "id" ? englishToIndonesian.get(core) : indonesianToEnglish.get(core);
    if (translatedAlias || translatedCore) return leading + prefix + (translatedAlias || translatedCore) + suffix + trailing;
  }
  return leading + translateDynamic(value, language) + trailing;
}

function translateTextNode(node: Text, language: PortalLanguage) {
  if (node.parentElement?.closest("[data-i18n-ignore]")) return;
  const current = node.data;
  const previous = textState.get(node);
  const source = previous && current === previous.rendered ? previous.source : current;
  const rendered = translatePortalText(source, language);
  textState.set(node, { source, rendered });
  if (current !== rendered) node.data = rendered;
}

function translateAttribute(element: Element, attribute: string, language: PortalLanguage) {
  const current = element.getAttribute(attribute);
  if (!current) return;
  const states = attributeState.get(element) || new Map<string, { source: string; rendered: string }>();
  const previous = states.get(attribute);
  const source = previous && current === previous.rendered ? previous.source : current;
  const rendered = translatePortalText(source, language);
  states.set(attribute, { source, rendered });
  attributeState.set(element, states);
  if (current !== rendered) element.setAttribute(attribute, rendered);
}

function translateTree(node: Node, language: PortalLanguage) {
  if (node instanceof Text) {
    if (node.parentElement?.tagName === "OPTION" && !node.parentElement.hasAttribute("value")) {
      node.parentElement.setAttribute("value", node.data.trim());
    }
    translateTextNode(node, language);
    return;
  }
  if (!(node instanceof Element) || node.closest("[data-i18n-ignore]")) return;
  for (const attribute of ["placeholder", "title", "aria-label", "alt"]) translateAttribute(node, attribute, language);
  for (const child of node.childNodes) translateTree(child, language);
}

export function PortalLanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<PortalLanguage>(() => {
    if (typeof window === "undefined") return "id";
    const saved = window.localStorage.getItem(STORAGE_KEY);
    return saved === "id" || saved === "en" ? saved : "id";
  });

  useEffect(() => {
    window.localStorage.setItem(STORAGE_KEY, language);
    document.documentElement.lang = language;
    translateTree(document.body, language);
    const observer = new MutationObserver(mutations => {
      for (const mutation of mutations) {
        if (mutation.type === "characterData") translateTree(mutation.target, language);
        if (mutation.type === "attributes") translateTree(mutation.target, language);
        for (const added of mutation.addedNodes) translateTree(added, language);
      }
    });
    observer.observe(document.body, {
      subtree: true,
      childList: true,
      characterData: true,
      attributes: true,
      attributeFilter: ["placeholder", "title", "aria-label", "alt"],
    });
    return () => observer.disconnect();
  }, [language]);

  return <LanguageContext.Provider value={{ language, setLanguage: setLanguageState }}>{children}</LanguageContext.Provider>;
}

export function usePortalLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error("usePortalLanguage must be used inside PortalLanguageProvider");
  return context;
}

export function PortalLanguageSwitcher({ className = "" }: { className?: string }) {
  const { language, setLanguage } = usePortalLanguage();
  return <label className={`portal-language-switcher ${className}`} data-i18n-ignore>
    <span aria-hidden="true">◎</span>
    <select aria-label="Bahasa / Language" value={language} onChange={event => setLanguage(event.target.value as PortalLanguage)}>
      <option value="id">Bahasa Indonesia</option>
      <option value="en">English</option>
    </select>
  </label>;
}
