import { env } from "cloudflare:workers";

type D1Row = Record<string, string | number | null>;
const tableFor:Record<string,string>={application:"applications",task:"tasks",submission:"submissions",creatorTask:"creator_tasks",appExpansion:"app_expansion_requests",streakRequest:"streak_requests",paymentForm:"payment_forms",creatorProfile:"creator_profiles",reward:"rewards"};
const allowed:Record<string,string[]>={
  applications:["id","name","handle","city","province","category","product","followers","status","score","submitted","avatar","email","whatsapp","date_of_birth","tiktok_url","instagram_url","threads_url","tiktok_followers","instagram_followers","threads_followers","interested_apps","features_used","motivation","impressions","decline_reason"],
  tasks:["id","title","product","platform","deadline","joined","budget","status","progress","cover","niches","brief","reference_link","tutorial_link","starts_at"],
  submissions:["id","creator","task","product","platform","views","ai_views","total_engagement","analytics_status","recommendation","confidence","status","submitted","avatar","post_url","published_at","boost_code","evidence_key","evidence_name","engagement_rate","whatsapp","submitted_at","qualification_reason"],
  creator_tasks:["id","creator","task_id","joined_at","status"],
  app_expansion_requests:["id","creator","current_apps","requested_apps","reason","status","submitted"],
  streak_requests:["id","creator","completed_tasks","selected_app","status","vip_code","submitted","reviewed_at","start_task_count","started_at"],
  payment_forms:["id","product","month","url"],
  creator_profiles:["id","creator","niches","avatar_key","avatar_name","threads_url","whatsapp"],
  rewards:["id","creator","task","product","views","type","amount","status","submission_id","payment_form_checked","paid_at","failure_reason"],
};
const tables=[
  `CREATE TABLE IF NOT EXISTS applications (id TEXT PRIMARY KEY,name TEXT NOT NULL,handle TEXT NOT NULL,city TEXT NOT NULL,province TEXT NOT NULL DEFAULT '',category TEXT NOT NULL,product TEXT NOT NULL,followers TEXT NOT NULL,status TEXT NOT NULL,score INTEGER NOT NULL DEFAULT 0,submitted TEXT NOT NULL,avatar TEXT NOT NULL,email TEXT NOT NULL DEFAULT '',whatsapp TEXT NOT NULL DEFAULT '',date_of_birth TEXT NOT NULL DEFAULT '',tiktok_url TEXT NOT NULL DEFAULT '',instagram_url TEXT NOT NULL DEFAULT '',threads_url TEXT NOT NULL DEFAULT '',tiktok_followers TEXT NOT NULL DEFAULT '',instagram_followers TEXT NOT NULL DEFAULT '',threads_followers TEXT NOT NULL DEFAULT '',interested_apps TEXT NOT NULL DEFAULT '',features_used TEXT NOT NULL DEFAULT '',motivation TEXT NOT NULL DEFAULT '',impressions TEXT NOT NULL DEFAULT '',decline_reason TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS tasks (id TEXT PRIMARY KEY,title TEXT NOT NULL,product TEXT NOT NULL,platform TEXT NOT NULL,deadline TEXT NOT NULL,joined INTEGER NOT NULL DEFAULT 0,budget INTEGER NOT NULL,status TEXT NOT NULL,progress INTEGER NOT NULL DEFAULT 0,cover TEXT NOT NULL,niches TEXT NOT NULL DEFAULT '',brief TEXT NOT NULL DEFAULT '',reference_link TEXT NOT NULL DEFAULT '',tutorial_link TEXT NOT NULL DEFAULT '',starts_at TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS submissions (id TEXT PRIMARY KEY,creator TEXT NOT NULL,task TEXT NOT NULL,product TEXT NOT NULL,platform TEXT NOT NULL,views INTEGER NOT NULL,ai_views INTEGER NOT NULL,total_engagement INTEGER NOT NULL DEFAULT 0,analytics_status TEXT NOT NULL DEFAULT 'Pending AI extraction',recommendation TEXT NOT NULL,confidence INTEGER NOT NULL,status TEXT NOT NULL,submitted TEXT NOT NULL,avatar TEXT NOT NULL,post_url TEXT NOT NULL DEFAULT '',published_at TEXT NOT NULL DEFAULT '',boost_code TEXT NOT NULL DEFAULT '',evidence_key TEXT NOT NULL DEFAULT '',evidence_name TEXT NOT NULL DEFAULT '',engagement_rate REAL NOT NULL DEFAULT 0,whatsapp TEXT NOT NULL DEFAULT '',submitted_at TEXT NOT NULL DEFAULT '',qualification_reason TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS creator_tasks (id TEXT PRIMARY KEY,creator TEXT NOT NULL,task_id TEXT NOT NULL,joined_at TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'Joined',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS app_expansion_requests (id TEXT PRIMARY KEY,creator TEXT NOT NULL,current_apps TEXT NOT NULL,requested_apps TEXT NOT NULL,reason TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'In review',submitted TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS streak_requests (id TEXT PRIMARY KEY,creator TEXT NOT NULL,completed_tasks INTEGER NOT NULL,selected_app TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'In review',vip_code TEXT NOT NULL DEFAULT '',submitted TEXT NOT NULL,reviewed_at TEXT NOT NULL DEFAULT '',start_task_count INTEGER NOT NULL DEFAULT 0,started_at TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS payment_forms (id TEXT PRIMARY KEY,product TEXT NOT NULL,month TEXT NOT NULL,url TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS creator_profiles (id TEXT PRIMARY KEY,creator TEXT NOT NULL,niches TEXT NOT NULL DEFAULT '',avatar_key TEXT NOT NULL DEFAULT '',avatar_name TEXT NOT NULL DEFAULT '',threads_url TEXT NOT NULL DEFAULT '',whatsapp TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS rewards (id TEXT PRIMARY KEY,creator TEXT NOT NULL,task TEXT NOT NULL,product TEXT NOT NULL,views INTEGER NOT NULL,type TEXT NOT NULL,amount INTEGER NOT NULL,status TEXT NOT NULL,submission_id TEXT NOT NULL DEFAULT '',payment_form_checked INTEGER NOT NULL DEFAULT 0,paid_at TEXT NOT NULL DEFAULT '',failure_reason TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE TABLE IF NOT EXISTS audit_logs (id INTEGER PRIMARY KEY AUTOINCREMENT,actor TEXT NOT NULL,action TEXT NOT NULL,entity TEXT NOT NULL,entity_id TEXT NOT NULL,payload TEXT NOT NULL,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`,
  `CREATE INDEX IF NOT EXISTS idx_applications_status ON applications(status)`,
  `CREATE INDEX IF NOT EXISTS idx_submissions_status ON submissions(status)`,
  `CREATE INDEX IF NOT EXISTS idx_creator_tasks_creator ON creator_tasks(creator)`,
  `CREATE INDEX IF NOT EXISTS idx_app_expansion_requests_creator ON app_expansion_requests(creator)`,
  `CREATE INDEX IF NOT EXISTS idx_streak_requests_creator ON streak_requests(creator)`,
  `CREATE INDEX IF NOT EXISTS idx_streak_requests_status ON streak_requests(status)`,
  `CREATE INDEX IF NOT EXISTS idx_payment_forms_month_product ON payment_forms(month,product)`,
  `CREATE INDEX IF NOT EXISTS idx_creator_profiles_creator ON creator_profiles(creator)`,
  `CREATE INDEX IF NOT EXISTS idx_rewards_status ON rewards(status)`,
];
async function ensure(){const db=env.DB;await db.batch(tables.map(sql=>db.prepare(sql)));const rewardColumns=await db.prepare("PRAGMA table_info(rewards)").all<{name:string}>();if(!rewardColumns.results.some((column:{name:string})=>column.name==="failure_reason"))await db.prepare("ALTER TABLE rewards ADD COLUMN failure_reason TEXT NOT NULL DEFAULT ''").run();}
function camel(row:D1Row){return Object.fromEntries(Object.entries(row).map(([k,v])=>[k.replace(/_([a-z])/g,(_,c)=>c.toUpperCase()),v]));}
const validEvidenceKey=(key:unknown)=>typeof key==="string"&&key.startsWith("creator-evidence/");

export async function GET(){try{await ensure();const [a,t,s,c,x,k,p,f,r]=await env.DB.batch([env.DB.prepare("SELECT * FROM applications ORDER BY created_at DESC"),env.DB.prepare("SELECT * FROM tasks ORDER BY created_at DESC"),env.DB.prepare("SELECT * FROM submissions ORDER BY created_at DESC"),env.DB.prepare("SELECT * FROM creator_tasks ORDER BY created_at DESC"),env.DB.prepare("SELECT * FROM app_expansion_requests ORDER BY created_at DESC"),env.DB.prepare("SELECT * FROM streak_requests ORDER BY created_at DESC"),env.DB.prepare("SELECT * FROM payment_forms ORDER BY month DESC, product"),env.DB.prepare("SELECT * FROM creator_profiles ORDER BY updated_at DESC"),env.DB.prepare("SELECT * FROM rewards ORDER BY created_at DESC")]);return Response.json({applications:a.results.map(camel),tasks:t.results.map(camel),submissions:s.results.map(camel),creatorTasks:c.results.map(camel),appExpansionRequests:x.results.map(camel),streakRequests:k.results.map(camel),paymentForms:p.results.map(camel),creatorProfiles:f.results.map(camel),rewards:r.results.map(camel)});}catch{return Response.json({applications:[],tasks:[],submissions:[],creatorTasks:[],appExpansionRequests:[],streakRequests:[],paymentForms:[],creatorProfiles:[],rewards:[]});}}

export async function POST(request:Request){try{await ensure();const body=await request.json() as {entity?:string;item?:Record<string,unknown>};const table=body.entity?tableFor[body.entity]:undefined;if(!table||!body.item?.id)return Response.json({error:"Invalid entity"},{status:400});const item={...body.item};const renamed:Record<string,string>={aiViews:"ai_views",totalEngagement:"total_engagement",analyticsStatus:"analytics_status",dateOfBirth:"date_of_birth",tiktokUrl:"tiktok_url",instagramUrl:"instagram_url",threadsUrl:"threads_url",tiktokFollowers:"tiktok_followers",instagramFollowers:"instagram_followers",threadsFollowers:"threads_followers",interestedApps:"interested_apps",featuresUsed:"features_used",declineReason:"decline_reason",postUrl:"post_url",publishedAt:"published_at",boostCode:"boost_code",evidenceKey:"evidence_key",evidenceName:"evidence_name",engagementRate:"engagement_rate",submittedAt:"submitted_at",qualificationReason:"qualification_reason",taskId:"task_id",joinedAt:"joined_at",currentApps:"current_apps",requestedApps:"requested_apps",completedTasks:"completed_tasks",selectedApp:"selected_app",vipCode:"vip_code",reviewedAt:"reviewed_at",startTaskCount:"start_task_count",startedAt:"started_at",avatarKey:"avatar_key",avatarName:"avatar_name",referenceLink:"reference_link",tutorialLink:"tutorial_link",startsAt:"starts_at",submissionId:"submission_id",paymentFormChecked:"payment_form_checked",paidAt:"paid_at",failureReason:"failure_reason"};for(const [from,to] of Object.entries(renamed)){if(from in item){item[to]=item[from];delete item[from]}}const cols=allowed[table].filter(k=>item[k]!==undefined);if(!cols.includes("id"))return Response.json({error:"Missing id"},{status:400});const marks=cols.map(()=>"?").join(",");const updates=cols.filter(c=>c!=="id").map(c=>`${c}=excluded.${c}`).concat("updated_at=CURRENT_TIMESTAMP").join(",");const stmt=env.DB.prepare(`INSERT INTO ${table} (${cols.join(",")}) VALUES (${marks}) ON CONFLICT(id) DO UPDATE SET ${updates}`).bind(...cols.map(c=>item[c]));const actor=request.headers.get("oai-authenticated-user-email")||"local-demo";await env.DB.batch([stmt,env.DB.prepare("INSERT INTO audit_logs (actor,action,entity,entity_id,payload) VALUES (?,?,?,?,?)").bind(actor,"upsert",body.entity,String(item.id),JSON.stringify(item))]);return Response.json({ok:true});}catch(e){return Response.json({error:e instanceof Error?e.message:"Unable to save"},{status:500});}}

export async function DELETE(request:Request){try{await ensure();const body=await request.json() as {entity?:string;id?:string};const table=body.entity?tableFor[body.entity]:undefined;if(!table||!body.id)return Response.json({error:"Invalid entity"},{status:400});let evidenceToDelete="";if(body.entity==="submission"){const existing=await env.DB.prepare("SELECT evidence_key FROM submissions WHERE id = ?").bind(body.id).first<{evidence_key?:string}>();if(validEvidenceKey(existing?.evidence_key))evidenceToDelete=String(existing?.evidence_key)}const actor=request.headers.get("oai-authenticated-user-email")||"local-demo";await env.DB.batch([env.DB.prepare(`DELETE FROM ${table} WHERE id = ?`).bind(body.id),env.DB.prepare("INSERT INTO audit_logs (actor,action,entity,entity_id,payload) VALUES (?,?,?,?,?)").bind(actor,"delete",body.entity,body.id,JSON.stringify({id:body.id}))]);if(evidenceToDelete)await env.MEDIA.delete(evidenceToDelete);return Response.json({ok:true,evidenceDeleted:Boolean(evidenceToDelete)});}catch(e){return Response.json({error:e instanceof Error?e.message:"Unable to delete"},{status:500});}}
